import { useState } from 'react'
import { Building2, Check, Sparkles, Users } from 'lucide-react'

// Fixed visible states from OrganizationOnboarding.tsx. Organization summaries
// and join previews come solely from IPC, so no member/org identities are made up.
export function SourceOrganizationOnboarding({ state }) {
  if (state === 'loading' || state === 'join' || state === 'select') return <OrganizationLoading />
  return <OrganizationCreate />
}
function Frame({children}){return <main data-route="organization/onboarding" style={{display:'grid',width:'100%',height:'100%',minHeight:0,placeItems:'center',overflow:'auto',boxSizing:'border-box',padding:24,color:'var(--foreground)',background:'var(--background)'}}><div style={{width:'100%',maxWidth:576}}>{children}</div></main>}
function Spinner(){return <span aria-label="Loading" style={{width:20,height:20,border:'2px solid color-mix(in srgb,var(--foreground) 18%,transparent)',borderTopColor:'var(--foreground)',borderRadius:9999}}/>}
function OrganizationLoading(){return <Frame><div role="status" style={{display:'flex',flexDirection:'column',alignItems:'center',gap:12,padding:'64px 0'}}><Spinner/><p style={{margin:0,color:'var(--muted-foreground)',fontSize:14}}>Loading organizations...</p></div></Frame>}
function OrganizationCreate(){const[type,setType]=useState('creator_space');const[name,setName]=useState('');const[purpose,setPurpose]=useState('');const disabled=!name.trim()||!purpose.trim();return <Frame><section style={{padding:24,border:'1px solid color-mix(in srgb,var(--border) 60%,transparent)',borderRadius:16,background:'var(--background)',boxShadow:'var(--shadow-minimal)'}}><header style={{textAlign:'center'}}><span style={{display:'grid',width:48,height:48,placeItems:'center',margin:'0 auto',borderRadius:12,color:'var(--accent)',background:'color-mix(in srgb,var(--accent) 10%,transparent)'}}><Users size={24}/></span><h1 style={{margin:'16px 0 0',fontSize:20,fontWeight:600}}>Create your organization</h1><p style={{margin:'8px 0 0',color:'var(--muted-foreground)',fontSize:14}}>Create a business workspace or creator space to continue.</p></header><form onSubmit={event=>event.preventDefault()} style={{display:'grid',gap:20,marginTop:24}}><fieldset style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:12,border:0,padding:0,margin:0}}><legend style={{position:'absolute',width:1,height:1,overflow:'hidden',clip:'rect(0 0 0 0)'}}>Organization type</legend><TypeCard selected={type==='creator_space'} icon={Sparkles} title="Creator space" description="Publish apps and grow a member community." onClick={()=>setType('creator_space')}/><TypeCard selected={type==='enterprise_workspace'} icon={Building2} title="Business workspace" description="A controlled workspace for your company." onClick={()=>setType('enterprise_workspace')}/></fieldset><Field label="Organization name"><input value={name} maxLength={128} placeholder="e.g. Acme Studio" onChange={e=>setName(e.target.value)} style={inputStyle}/></Field><Field label="How will you use this space?"><textarea value={purpose} maxLength={512} placeholder="Describe what your team or community will do here" onChange={e=>setPurpose(e.target.value)} style={{...inputStyle,minHeight:96,height:'auto',padding:'8px 12px',resize:'none'}}/></Field><button data-testid="organization-create-submit" type="submit" disabled={disabled} style={{height:44,border:0,borderRadius:6,color:'var(--background)',background:'var(--foreground)',opacity:disabled?.5:1,fontSize:14,fontWeight:500}}>Create organization</button></form></section></Frame>}
function TypeCard({selected,icon:Icon,title,description,onClick}){return <button type="button" aria-pressed={selected} onClick={onClick} style={{position:'relative',padding:16,border:`1px solid ${selected?'var(--accent)':'color-mix(in srgb,var(--border) 70%,transparent)'}`,borderRadius:12,color:'var(--foreground)',background:selected?'color-mix(in srgb,var(--accent) 5%,transparent)':'transparent',textAlign:'left'}}>{selected&&<span style={{position:'absolute',top:12,right:12,display:'grid',width:20,height:20,placeItems:'center',borderRadius:9999,color:'var(--background)',background:'var(--accent)'}}><Check size={12}/></span>}<Icon size={20} color="var(--accent)"/><strong style={{display:'block',marginTop:12,fontSize:14,fontWeight:500}}>{title}</strong><small style={{display:'block',marginTop:4,color:'var(--muted-foreground)',fontSize:12,lineHeight:1.6}}>{description}</small></button>}
function Field({label,children}){return <label style={{display:'grid',gap:8,color:'var(--foreground)',fontSize:14,fontWeight:500}}>{label}{children}</label>}
const inputStyle={width:'100%',height:36,boxSizing:'border-box',padding:'0 12px',border:'1px solid color-mix(in srgb,var(--foreground) 15%,transparent)',borderRadius:6,outline:0,color:'var(--foreground)',background:'transparent',font:'inherit',fontSize:14,fontWeight:400}
