import {useEffect,useState,useSyncExternalStore} from 'react'
import {Paperclip,ArrowUp,Square,Inbox,Zap,DatabaseZap,Plus,FileText,Home,Bell} from 'lucide-react'
import {SourceResourceEmptyPanel} from '../source/ResourceEmptyPanels.jsx'
import {SourceBrowserEmptyState} from '../source/BrowserEmptyState.jsx'
import {SourcePoloShell} from '../source/PoloShell.jsx'
import {SourceFaithfulEmptyChat} from '../source/EmptyChat.jsx'
import {UserMessageBubble,AssistantMessageBubble} from '../source/ChatConversation.jsx'
import {EntityRow,ListBadge,SkillIcon,HeroSkillIcon,Hero,InfoPageContent,InfoSection,InfoTable,InfoCard,SourceIcon,HeroSourceIcon} from '../source/ResourceListDetail.jsx'
import {subscribe,getSnapshot,act,getDraft,setDraft,getSubmitted,getAttachment,setAttachment,canSend,canRead,blockingText,isSavedConversation,getConversationId,getAttachmentContent,actionEnabled,getSourceStatus,getPreferences,changePreference,savePreferences,preferencesDirty,discardPreferences,getActivity,getSkillSourceText,getImportedMessages,getTransferDraft,getTransferResult,selectTransferFile,transferSelectionToken,getImportedConversations,getImportedTitle,selectImportedConversation} from './runtime.js'

function Action({scene,edge,children,className='',before}){
 if(edge.key==='reselect')return <label className="mvp-action mvp-attach">重新选择文件<input type="file" aria-label="重新选择文件" data-go={edge.to} data-transition={edge.id} onChange={async e=>{const file=e.target.files?.[0];if(file){setAttachment(scene.scope,file.name,file.type.startsWith('text/')&&file.size<2000000?await file.text():null);act('reselect')}}}/></label>
 return <button type="button" aria-label={edge.label} hidden={!actionEnabled(scene.scope,edge.key)} disabled={!actionEnabled(scene.scope,edge.key)} className={'mvp-action '+className} data-go={edge.to} data-transition={edge.id} onClick={()=>{if(scene.family==='preferences'&&preferencesDirty(scene.scope)){if(!window.confirm('有未保存的助手偏好。离开将放弃修改；选择取消继续编辑。'))return;discardPreferences(scene.scope)}before?.();act(edge.key)}}>{children||edge.label}</button>
}
function Actions({scene,area='body'}){return <div className="mvp-actions">{scene.transitions.filter(t=>t.area===area).map(t=><Action key={t.id} scene={scene} edge={t}/>)}</div>}
function Chat({scene}){
 const question=['question','reopen','answerfailed'].includes(scene.key),key=question?'question':'conversation'
 const [draft,changeDraft]=useState(()=>getDraft(scene.scope,key)),[localAttachment,setLocalAttachment]=useState(getAttachment(scene.scope))
 useEffect(()=>{changeDraft(getDraft(scene.scope,key));setLocalAttachment(getAttachment(scene.scope))},[scene.id,getConversationId(scene.scope)])
 const change=value=>{changeDraft(value);setDraft(scene.scope,value,key)}
 const permitted=canSend(scene.scope), readable=canRead(scene.scope)
 const generating=scene.key==='generating',fresh=['new','preblock'].includes(scene.key),scopeName=getImportedTitle(scene.scope)||(scene.scope==='personal'?'个人资料整理':'企业周报')
 const notices={budgetnotified:'已通知所有者调整企业预算。',budgetmemberchecking:'正在核对企业预算…',budgetmemberpending:'企业预算仍受限。',budgetmemberfailed:'企业预算查询失败。',budgetmemberresumed:'企业预算已恢复。',availability:'处理当前发送限制后，再回到会话发送。',returnstream:'已在浏览器完成充值？',checkingstream:'正在查询本次充值结果…',notyetstream:'尚未到账，已生成内容已保留。',failedstream:'查询失败，已生成内容已保留。',resumedstream:'积分可用，可以发送消息。',ownerchecking:'正在查询企业充值结果…',ownerpending:'企业积分尚未恢复。',ownerfailed:'企业积分查询失败。',budgetreturn:'已在浏览器调整预算？',budgetchecking:'正在查询企业预算…',budgetpending:'企业预算仍受限。',budgetfailed:'企业预算查询失败。',budgetresumed:'企业预算已恢复。',permission:'需要读取你选择的文件。是否允许本次访问？',permissiondenied:'文件访问权限被拒绝。请在系统设置 → 隐私与安全性 → 文件与文件夹中允许 Polo 访问，再重新请求。',permissiongranted:'已允许本次访问。',stopped:'已停止生成。',question:'需要汇总哪一个时间范围？',reopen:'需要汇总哪一个时间范围？',answered:'已收到你的回答，正在原会话中继续整理。',deferred:'已暂不回答。',expired:'这个问题已过期，请在原会话重新提问。',deleted:'原会话已删除或你已无权访问。',answerfailed:'回答尚未提交，请重试。',offline:'网络已断开，生成已暂停。',service:'服务暂时不可用，请稍后重试。',restored:'已重新验证，可以发送消息。',completezero:'本次生成已完成。',return:'已在浏览器完成充值？',ownerreturn:'已在浏览器处理企业额度？',preblock:'积分不足，请充值后查询结果。',cut:'积分不足，本次生成已停止。',checking:'正在查询本次充值结果…',notyet:'尚未到账，请稍后再查。',queryfailed:'查询失败，积分状态尚未更新。',resumed:'积分已到账，可以发送消息。',notify:'企业积分不足，请通知所有者处理。',notified:'已通知所有者，等待处理。',budget:'企业预算已达上限，请通知所有者调整。',budgetowner:'企业预算已达上限。',ownerblock:'企业积分不足。',ownerresumed:'企业积分已可用，可以发送消息。'}
 const send=scene.transitions.find(t=>['send','stop'].includes(t.key))
 const questionAction=scene.transitions.find(t=>t.key==='answer')
 const filePicker=<label className="mvp-attach"><Paperclip size={16}/><span>附加文件</span><input aria-label="附加文件" type="file" onChange={async e=>{const file=e.target.files?.[0];if(file){setAttachment(scene.scope,file.name,file.type.startsWith('text/')&&file.size<2000000?await file.text():null);setLocalAttachment(file.name)}}}/></label>
 const transcript=<>
  {!fresh&&scene.key!=='deleted'&&readable&&isSavedConversation(scene.scope)&&<><UserMessageBubble text={scene.scope==='personal'?'请整理这份资料，保留关键结论。':'请汇总本周企业项目进展。'}/><AssistantMessageBubble text={generating?'正在整理资料中的关键结论…':'已整理第一部分：本周的主要进展与后续待办。'}/></>}
  {readable&&getImportedMessages(scene.scope)?.map((m,i)=>m.role==='user'?<UserMessageBubble key={'i'+i} text={m.text}/>:<AssistantMessageBubble key={'i'+i} text={m.text}/>)}
  {readable&&getSubmitted(scene.scope).map((text,i)=><UserMessageBubble key={i} text={text}/>)}
  {readable&&!getImportedMessages(scene.scope)&&!isSavedConversation(scene.scope)&&!fresh&&scene.key!=='deleted'&&<AssistantMessageBubble text={generating?'正在整理你发送的材料…':'已整理第一部分：本周的主要进展与后续待办。'}/>}

  {['cut','stopped'].includes(scene.key)&&<div role="status" className="mvp-alert">{notices[scene.key]}<Actions scene={scene}/></div>}
  {question&&<InfoCard><div className="mvp-question"><p>{notices[scene.key]}</p><textarea aria-label="回答问题" value={draft} placeholder="例如：本周一到周五" onChange={e=>change(e.target.value)}/><div className="mvp-actions">{questionAction&&<button className="mvp-action primary" disabled={!draft.trim()||!permitted} data-transition={questionAction.id} data-go={questionAction.to} onClick={()=>act('answer')}>提交回答</button>}{scene.transitions.filter(t=>t.key==='defer').map(t=><Action key={t.id} scene={scene} edge={t}/>)}</div></div></InfoCard>}
  {scene.family==='files'&&readable&&!isSavedConversation(scene.scope)&&!getAttachment(scene.scope)&&<div><p>当前会话暂无文件。</p><Actions scene={scene} area="files"/></div>}
  {scene.family==='files'&&readable&&(isSavedConversation(scene.scope)||getAttachment(scene.scope))&&<InfoCard><div className="mvp-question"><strong>{scene.key==='missing'?'文件不可用':scene.key==='viewer'?'资料汇总.md':scene.key==='attachment'?(getAttachment(scene.scope)||'项目资料.pdf'):'会话文件'}</strong><p>{scene.key==='missing'?'原文件已移动或删除，请重新选择。':scene.key==='attachment'?(getAttachmentContent(scene.scope)||'此文件暂不支持文本预览。'):scene.key==='viewer'?'本周主要进展\n一、已整理需求材料。\n二、待核对后提交总结。':`附件：${getAttachment(scene.scope)||'项目资料.pdf'}${isSavedConversation(scene.scope)?' · 生成文件：资料汇总.md':''}`}</p><Actions scene={scene} area="files"/></div></InfoCard>}
 </>
 const composer=question?null:<form onSubmit={e=>{e.preventDefault();if(send&&!generating)act('send')}} className="mvp-composer"><textarea aria-label="消息" placeholder="想做什么?" value={draft} onChange={e=>change(e.target.value)}/>{localAttachment&&<span className="mvp-attached">{localAttachment}</span>}<div className="mvp-composer-footer">{filePicker}<span className="mvp-input-context">当前空间</span><span style={{flex:1}}/>{send?<button className="mvp-send" type={generating?'button':'submit'} disabled={!generating&&(!draft.trim()||!permitted)} aria-label={send.label} data-go={send.to} data-transition={send.id} onClick={generating?()=>act('stop'):undefined}>{generating?<Square size={14}/>:<ArrowUp size={16}/>}</button>:<button className="mvp-send" disabled aria-label="发送消息"><ArrowUp size={16}/></button>}</div></form>
 return <SourceFaithfulEmptyChat mvp={{title:fresh?'新聊天':scopeName,transcript,badges:scene.family!=='files'&&readable?<Actions scene={scene} area="files"/>:null,notice:!['cut','stopped'].includes(scene.key)&&<>{!notices[scene.key]&&blockingText(scene.scope)&&<p role="status">{blockingText(scene.scope)}</p>}{notices[scene.key]&&<p role="status">{notices[scene.key]}</p>}<Actions scene={scene}/></>,composer}}/>
}
function SkillNavigator({scene}){
 if(scene.key==='empty-skills')return <div className="source-navigator__header"><strong>技能</strong></div>
 return <><div className="source-navigator__header"><strong>技能</strong></div><div className="mvp-list"><EntityRow icon={<SkillIcon emoji="📋"/>} title={scene.scope==='personal'?'资料研究':'销售周报'} selected badges={<ListBadge tint="accent">{scene.scope==='personal'?'晨星增长圈 · 晨星设计圈':'晨星科技共享'}</ListBadge>}/><EntityRow icon={<SkillIcon emoji="✨"/>} title="资料研究" badges={<ListBadge tint="project">Polo 内置</ListBadge>}/></div></>
}
function Skills({scene}){
 const title=scene.scope==='personal'?'资料研究':'销售周报',restricted=scene.authorization==='已失效',remove=scene.key==='restricted-remove'||scene.key==='remove'||scene.legacyView==='remove'
 if(scene.key==='empty-skills')return <SourceResourceEmptyPanel kind="skills" actions={false}/>
 return <div className="mvp-detail">{remove&&<div className="source-navigator__header"><span className="source-navigator__header-title">卸载本机副本</span></div>}<InfoPageContent>
 <Hero avatar={<HeroSkillIcon emoji="📋"/>} title={title} tagline="整理材料与进展，形成可核对的报告草稿"/>
 <InfoSection title="来源与使用状态"><InfoTable rows={[
 ['来源',getSkillSourceText(scene.scope)],['来源授权',scene.authorization],['本人启用',scene.enabled?'已启用':'未启用'],['本机准备',scene.device],['本机版本',scene.device==='未安装'?'—':scene.version],['内置资料研究',scene.builtin===false||scene.key==='builtinoff'?'已停用':'已启用']
 ]}/></InfoSection>
 {scene.key==='installing'&&<p role="status">正在下载并验证技能包…</p>}
 {scene.key==='installfailed'&&<p className="mvp-alert">下载失败，请检查网络后重试。本人的启用设置已保留。</p>}
 {scene.key==='updatefailed'&&<p className="mvp-alert">更新失败，仍使用已验证的 {scene.version} 版本。</p>}
 {restricted&&<p className="mvp-alert">最后一个有效来源已失效，当前不可调用。已保存的对话仍可查看。</p>}
 {scene.key==='denied'&&<p className="mvp-alert">你尚未获得此技能的使用授权。{scene.scope==='personal'?'请向提供该技能的圈子确认资格。':'请联系企业管理员。'}</p>}
 {scene.authorization==='另一来源有效'&&scene.scope==='personal'&&<p>仍可通过其他有效来源使用；失效来源不再提供调用授权。</p>}
 {remove&&<p>将删除这台设备的技能副本。原对话及附件保留。</p>}
 <Actions scene={scene}/><InfoSection title="版本更新"><p className="mvp-description">最新可用版本：1.1.0</p><p className="mvp-description">1.1.0：改善资料摘要和引用整理。更新用于后续调用，已运行的任务不切换版本。</p></InfoSection><InfoSection title="说明"><p className="mvp-description">使用当前空间中已授权的数据源整理资料。执行前请核对文件范围与输出内容。</p></InfoSection>
 </InfoPageContent></div>
}
function Sources({scene}){
 const [token,setToken]=useState(()=>getDraft(scene.scope,'source-auth'))
 if(scene.key==='automations'||scene.key==='empty-sources')return <SourceResourceEmptyPanel kind={scene.key==='automations'?'automations':'sources'} actions={false}/>
 if(scene.key==='browser')return <SourceBrowserEmptyState suggestions={false}/>
 return <div className="mvp-detail"><div className="source-navigator__header"><strong>{scene.key==='automations'?'自动化':scene.key==='browser'?'浏览器':'数据源与工具'}</strong></div><InfoPageContent><Hero avatar={<HeroSourceIcon type="mcp"/>} title={scene.key==='automations'?'暂无自动化':scene.key==='browser'?'尚未打开网页':'项目资料'} tagline={scene.scope==='personal'?'我的空间的数据源':'晨星科技的数据源'}/>
 {scene.key==='sourceauth'?<label>访问凭证<input type="password" aria-label="访问凭证" value={token} onChange={e=>{setToken(e.target.value);setDraft(scene.scope,e.target.value,"source-auth")}}/></label>:<InfoSection title="连接与权限"><InfoTable rows={[["类型","MCP"],["连接",({connected:'已连接',failed:'连接失败',denied:'未获得访问权限',disconnected:'未连接',connecting:'正在连接…',auth:'需要认证'}[getSourceStatus(scene.scope)])],['read_file','允许'],['write_file','询问'],['run_command','询问']]}/></InfoSection>}
 <div className="mvp-actions">{scene.transitions.filter(t=>t.area==='body').map(t=><button key={t.id} className="mvp-action" disabled={scene.key==='sourceauth'&&t.key==='connect'&&!token.trim()} data-go={t.to} data-transition={t.id} onClick={()=>act(t.key)}>{t.label}</button>)}</div></InfoPageContent></div>
}
function Navigator({scene}){
 if(scene.family==='skills')return <SkillNavigator scene={scene}/>
 if(scene.key==='empty-sources')return <div className="source-navigator__header"><strong>数据源</strong></div>
 if(scene.family==='sources')return <><div className="source-navigator__header"><strong>数据源</strong></div><div className="mvp-list"><EntityRow icon={<SourceIcon type="mcp"/>} title="项目资料" selected badges={<ListBadge tint="accent">{scene.scope==='personal'?'我的空间':'晨星科技'}</ListBadge>}/></div></>
 return <><div className="source-navigator__header"><span className="source-navigator__header-title">所有会话</span></div><div className="source-navigator__list"><div className="mvp-list">{scene.transitions.filter(t=>t.key==='sessions').map(t=><Action key={t.id} edge={t} scene={scene} className="mvp-session" before={()=>{}}>{scene.scope==='personal'?'个人资料整理':'企业周报'}</Action>)}{scene.transitions.filter(t=>t.key==='open-imported').map(t=>getImportedConversations(scene.scope).length?getImportedConversations(scene.scope).map(c=><button key={c.id} className="mvp-action mvp-session polo-imported-session" data-go={t.to} data-transition={t.id} onClick={()=>selectImportedConversation(scene.scope,c.id)} aria-label={'打开导入对话：'+c.title+' · '+c.preview}><strong>{c.title}</strong><small>{c.preview}</small></button>):<button key={t.id} hidden disabled data-go={t.to} data-transition={t.id}>打开导入对话</button>)}</div></div></>
}

function HostChrome({scene}){
 const edge=key=>scene.transitions.find(t=>t.key===key)
 const control=(key,children,cls='')=>edge(key)&&<Action scene={scene} edge={edge(key)} className={cls}>{children}</Action>
 return <header className="polo-host-bar" aria-label="Polo 顶栏"><div className="polo-window-dots" role="img" aria-label="macOS 窗口控制"><i/><i/><i/></div><div className="polo-host-brand"><b>P</b><span>Polo</span></div><nav aria-label="应用标签">{control('home',<><Home size={14}/> 首页</>)}{scene.family!=='skills'&&<div className="polo-host-tab"><span>Polo 助手</span>{control('closeidle','×','polo-tab-close')}{control('closeactive','×','polo-tab-close')}</div>}</nav><div className="polo-host-actions">{control('runtime','后台任务')}<span className="polo-host-space">{scene.scope==='personal'?'我的空间':'晨星科技'}</span>{control('notification',<Bell size={16}/>)}{control('account','王','polo-avatar')}</div></header>
}
function SkillLibrary({scene}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('全部技能'),[source,setSource]=useState('全部来源'),[selected,select]=useState('circle'),[detailOpen,setDetailOpen]=useState(false)
 useEffect(()=>{select(['builtinon','builtinoff'].includes(scene.key)?'builtin':'circle')},[scene.key])
 const name=scene.scope==='personal'?'资料研究':'销售周报',empty=scene.key==='empty-skills'
 const match=!empty&&(name+' 整理材料 报告').includes(query)&& (filter==='全部技能'||filter==='已启用'&&scene.enabled||filter==='待准备'&&scene.device!=='就绪'||filter==='有更新'&&scene.version!=='1.1.0'||filter==='受限'&&scene.authorization==='已失效')&&source!=='Polo 内置'
 const builtin=!empty&&'资料研究 Polo 内置'.includes(query)&&['全部技能','已启用'].includes(filter)&&(filter!=='已启用'||scene.builtin!==false)&&['全部来源','Polo 内置'].includes(source)
 return <div className={'polo-skill-manager '+(detailOpen?'show-skill-detail':'')}><div className="polo-resource-heading"><div><h1>技能</h1><p>管理当前空间的技能、来源与版本</p></div><div className="polo-resource-tools"><label>搜索技能<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="名称或用途"/></label>{scene.transitions.filter(t=>t.key==='assistant').map(t=><Action key={t.id} scene={scene} edge={t}/>)}</div></div><div className="polo-skill-columns"><aside className="source-sidebar polo-skill-filters" aria-label="技能筛选">{['全部技能','已启用','待准备','有更新','受限'].map(v=><button key={v} className={filter===v?'selected':''} onClick={()=>setFilter(v)}>{v}</button>)}<label>来源<select value={source} onChange={e=>setSource(e.target.value)}><option>全部来源</option><option>Polo 内置</option>{scene.scope==='personal'?<><option>晨星增长圈</option><option>晨星设计圈</option></>:<option>晨星科技</option>}</select></label></aside><section className="polo-skill-results" aria-label="技能列表"><p className="polo-list-count">{Number(match)+Number(builtin)} 项技能</p>{match&&<button type="button" onClick={()=>{select('circle');setDetailOpen(true)}} aria-label="查看来源技能" className={'polo-skill-summary '+(selected==='circle'?'selected':'')}><strong>{name}</strong><p>{getSkillSourceText(scene.scope)}</p><small>{scene.enabled?'已启用':'未启用'} · {scene.device} · {scene.version||'未安装'}</small></button>}{builtin&&<button type="button" onClick={()=>{select('builtin');setDetailOpen(true)}} aria-label="查看内置技能" className={'polo-skill-summary '+(selected==='builtin'?'selected':'')}><strong>资料研究</strong><p>Polo 内置</p><small>{scene.builtin===false?'已停用':'已启用'}</small></button>}{!match&&!builtin&&<p className="polo-library-empty">没有匹配的技能。请调整搜索或筛选。</p>}</section><section className="polo-skill-detail" aria-label="技能详情"><button className="mvp-action polo-skill-back" onClick={()=>setDetailOpen(false)}>返回技能列表</button><div hidden={!match||selected==='builtin'}><Skills scene={scene}/></div><div hidden={!builtin||(selected!=='builtin'&&match)} className="polo-library-empty"><h2>资料研究</h2><p>Polo 内置 · 随客户端提供</p><p>启用状态：{scene.builtin===false?'已停用':'已启用'}</p><Actions scene={scene} area="builtin"/><p>随 Polo 版本维护，不使用圈子版本，也不依赖圈子订阅。</p></div>{!match&&!builtin&&<div className="polo-library-empty">暂无匹配的技能。清空搜索或调整筛选后重试。</div>}</section></div><div className="polo-resource-footer">{scene.transitions.filter(t=>['new','sessions','skills','sources'].includes(t.key)).map(t=><Action key={t.id} scene={scene} edge={t}>{t.key==='skills'?'返回完整技能列表':t.key==='new'?'新建助手会话':t.key==='sources'?'助手数据源':t.label}</Action>)}</div></div>
}
function AssistantPreferences({scene}){
 const [section,setSection]=useState('输入与发送'),[saved,setSaved]=useState(''),[values,setValues]=useState(()=>getPreferences(scene.scope))
 useEffect(()=>{setValues(getPreferences(scene.scope));setSaved(scene.key==='preferences-savefailed'?'未能保存偏好。修改已保留，请重试。':'')},[scene.scope,scene.key])
 const change=(key,value)=>{changePreference(scene.scope,key,value);setValues(getPreferences(scene.scope));setSaved('尚未保存')}
 return <div className="polo-preferences">{scene.transitions.filter(t=>t.key==='preferences').map(t=><Action key={t.id} scene={scene} edge={t}/>)}<h1>助手偏好</h1><p>作用于{scene.scope==='personal'?'我的空间':'晨星科技'}中的 Polo 助手。账号、外观与网络在 Polo 设置中管理。</p><div className="polo-preferences-grid"><nav className="source-sidebar">{['输入与发送','回答偏好','会话标签','工具权限'].map(v=><button className={v===section?'selected':''} key={v} onClick={()=>setSection(v)}>{v}</button>)}</nav><form onSubmit={e=>{e.preventDefault();savePreferences(scene.scope);setSaved('偏好已保存。')}}><h2>{section}</h2>{section==='输入与发送'?<><label>发送消息<select value={values.send} onChange={e=>change('send',e.target.value)}><option value="enter">Enter 发送，Shift + Enter 换行</option><option value="cmd">⌘ + Enter 发送</option></select></label><label><input type="checkbox" checked={values.spell} onChange={e=>change('spell',e.target.checked)}/> 输入时检查拼写</label></>:section==='回答偏好'?<><label>助手如何称呼你<input value={values.name} onChange={e=>change('name',e.target.value)}/></label><label>回答偏好<textarea value={values.answer} onChange={e=>change('answer',e.target.value)} placeholder="例如：简洁回答，先给结论"/></label></>:section==='会话标签'?<label>会话标签<input value={values.labels} onChange={e=>change('labels',e.target.value)}/></label>:<><p>权限只控制助手工具调用，不改变系统授权或当前空间的数据权限。</p>{[['read','读取文件'],['write','写入文件'],['command','执行命令']].map(([key,label])=><label key={key}>{label}<select value={values[key]} onChange={e=>change(key,e.target.value)}><option value="ask">每次询问</option><option value="deny">拒绝</option></select></label>)}</>}<button type="submit" className="mvp-action primary">{scene.key==='preferences-savefailed'?'重试保存':'保存偏好'}</button><p role="status">{saved}</p></form></div></div>
}
function AssistantActivity({scene}){const active=getActivity(scene.scope);return <div className="polo-preferences"><h1>助手任务</h1><p>{scene.scope==='personal'?'我的空间':'晨星科技'}</p>{active.running?<section className="polo-library-empty"><h2>Polo 助手正在执行</h2><p>任务在当前空间中继续，生成内容保留在原会话。</p></section>:<p>当前没有运行中的助手任务。</p>}<Actions scene={scene}/>{scene.transitions.filter(t=>t.key==='preferences').map(t=><Action key={t.id} scene={scene} edge={t}/>)}</div>}
function CloseAssistant({scene}){return <div className="polo-close"><section role="dialog" aria-label="关闭 Polo 助手"><h1>{scene.key==='closefailed'?'未能停止任务':'助手仍在执行任务'}</h1><p>{scene.key==='closefailed'?'尚未确认任务已停止，当前标签保持打开。可以重试停止，或取消关闭。':'关闭视图不会删除原对话。后台继续仍会执行任务，并产生相应计算费用。'}</p><Actions scene={scene}/></section></div>}

function TransferContent({scene}){
 const pending=getTransferDraft(scene.scope),result=getTransferResult(scene.scope),preview=scene.key==='transfer-preview';
 return <div className="polo-preferences polo-transfer"><h1>{scene.title.split(' · ')[0]}</h1><p>{scene.scope==='personal'?'我的空间':'晨星科技'} · 原对话保持不变</p>
 {scene.key==='legacy-isolation'?<p role="status">这些旧数据尚不能核对归属，当前不可打开或导入。完成账号与原空间归属核验前，数据保持隔离，不自动归入个人空间。</p>:<>
 {scene.key==='transfer-export'&&<><p>当前允许转移消息文本。附件与其他未获允许的内容不包含在本次导出中。</p><p>数据源连接、凭证、工具授权与隐藏上下文不会导出。另一空间需要由你主动导入，系统会建立新对话。</p></>}
 {scene.key==='transfer-exported'&&<p role="status">已生成可保存的对话文件。尚未向其他空间导入，也未改变原空间权限。</p>}
 {scene.key==='transfer-import'&&<><p>选择已导出的对话文件。先核对可导入内容，确认后才在当前空间建立新对话。</p><label className="mvp-action">选择导出文件<input aria-label="选择导出文件" type="file" accept="application/json,.json" data-go={scene.transitions.find(t=>t.key==='select-import').to} data-transition={scene.transitions.find(t=>t.key==='select-import').id} onChange={async e=>{const file=e.target.files?.[0],token=transferSelectionToken();if(file){try{selectTransferFile(scene.scope,file.size<2000000?await file.text():'',token)}catch{selectTransferFile(scene.scope,'',token)}}}}/></label>{pending?.error&&<p role="alert">{pending.error}</p>}</>}
 {preview&&<>{pending?.messages?<><p>将导入 {pending.messages.length} 条消息，建立独立新对话；不会运行原任务或继承源空间权限。</p><ul>{pending.messages.map((m,i)=><li key={i}>{m.role==='user'?'用户':'助手'}：{m.text}</li>)}</ul></>:<p>尚未选择可导入内容。请取消并重新选择文件。</p>}</>}
 {scene.key==='transfer-done'&&<p role="status">{result?`已在当前空间建立「${result.title}」，包含 ${result.count} 条消息。`:'没有本次导入记录。请从导入入口选择文件并确认。'} 原数据源和工具尚未获得授权；没有自动执行任务。</p>}
 {scene.key==='transfer-invalid'&&<p role="alert">文件无法校验，未建立对话，也未产生可访问的部分内容。请重新选择受支持的导出文件。</p>}
 </>}
 <div className="mvp-actions">{scene.transitions.filter(t=>t.area==='body'&&t.key!=='select-import').map(t=><Action key={t.id} scene={scene} edge={t}/>)}</div></div>
}

export function MvpAssistant(){
 const {scene,settings,resetVersion}=useSyncExternalStore(subscribe,getSnapshot,getSnapshot)
 useEffect(()=>{document.documentElement.dataset.theme=settings.theme;document.documentElement.lang=settings.language;document.body.dataset.currentScene=scene.id},[scene.id,settings])
 return <div data-product-surface className="mvp-root" key={resetVersion}><div data-prototype-scene={scene.id} className="mvp-scene">
 <HostChrome scene={scene}/>{scene.family==='transfer'?<TransferContent scene={scene}/>:scene.family==='skills'?<SkillLibrary scene={scene}/>:scene.family==='preferences'?<AssistantPreferences scene={scene}/>:scene.family==='activity'?<AssistantActivity scene={scene}/>:scene.family==='close'?<CloseAssistant scene={scene}/>:<div className="polo-assistant-body"><SourcePoloShell mvp={{scope:scene.scope==='personal'?'我的空间':'晨星科技',navigation:<nav className="source-sidebar__nav">{scene.transitions.filter(t=>t.area==='nav'&&(t.key!=='sessions'||['skills','sources'].includes(scene.family))).map(t=><Action key={t.id} scene={scene} edge={t} className={'source-nav-item '+(t.key==='new'?'source-new-session':'')}><span>{t.key==='new'?<Plus size={14}/>:t.key==='skills'?<Zap size={14}/>:t.key==='sources'?<DatabaseZap size={14}/>:<Inbox size={14}/>}</span>{t.label}</Action>)}</nav>}} navigator={<Navigator scene={scene}/>}>{scene.family==='skills'?<Skills key={scene.id} scene={scene}/>:scene.family==='sources'?<Sources key={scene.id} scene={scene}/>:<Chat scene={scene}/>}</SourcePoloShell><div className="polo-assistant-preferences">{scene.transitions.filter(t=>t.key==='preferences').map(t=><Action key={t.id} scene={scene} edge={t}/>)}</div></div>}
 </div></div>
}
