import React, { useMemo, useState } from 'react'
import { Icon, Logo } from '../regions/icons.jsx'
import { Dialog } from '../runtime/interaction-primitives.jsx'
import { navigate } from '../runtime/state.js'
import { sessions, products, sources, skills, automations, settingsGroups, notifications } from '../fixtures/data.js'

function PageHeading({ eyebrow, title, description, action }) {
  return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1>{description && <p>{description}</p>}</div>{action && <div className="heading-context">{action}</div>}</div>
}

function EmptyState({ icon = 'spark', title, description, action, onAction, failure = false }) {
  return <div className="state-card"><div><div className={'state-icon' + (failure ? ' failure' : '')}><Icon name={icon} size={22}/></div><h2>{title}</h2><p>{description}</p>{action && <div className="onboarding-actions"><button className="button primary" onClick={onAction}>{action}</button></div>}</div></div>
}

export function LifecycleScene({ query }) {
  const [busy, setBusy] = useState(query.scene === 'splash' || query.state === 'loading')
  const isSplash = query.scene === 'splash'
  const configs = {
    onboarding: { eyebrow: 'First launch', title: query.state === 'admin-login' ? 'Connect your admin account' : 'Welcome to Polo', text: query.state === 'git-bash' ? 'Polo needs Git Bash to run workspace actions on Windows.' : 'Set up a private workspace for your team and keep the first run reversible.', action: query.state === 'admin-login' ? 'Continue with admin' : 'Start setup', next: query.state === 'admin-login' ? 'welcome' : 'onboarding' },
    reauth: { eyebrow: 'Workspace locked', title: 'Re-authenticate to continue', text: 'Your local session is protected. Unlock it to return to the current workspace.', action: 'Unlock workspace', next: 'home' },
    'workspace-picker': { eyebrow: 'Choose a workspace', title: query.state === 'error' ? 'Workspace unavailable' : 'Where should we work?', text: query.state === 'error' ? 'The last workspace could not be reached. Try another folder or reconnect the server.' : 'Choose a recent workspace or connect a new local folder.', action: query.state === 'error' ? 'Try again' : 'Open Polo workspace', next: 'home' },
    organization: { eyebrow: 'Creator Space', title: query.state === 'create' ? 'Create an organization' : query.state === 'join' ? 'Join your organization' : 'Select an organization', text: 'Organization membership controls shared apps, skills, and artifact publishing.', action: query.state === 'create' ? 'Create organization' : 'Continue', next: 'home' },
  }
  const config = configs[query.scene]
  if (isSplash) {
    if (busy) window.setTimeout(() => setBusy(false), 900)
    return <div className="lifecycle-screen"><div className="onboarding-card splash-mark"><div className="brand-symbol"><Logo compact/></div><h1>Starting Polo</h1><p>Restoring the local workspace and transport connection…</p><div className="spinner" style={{ marginTop: 22 }} aria-label="Loading"/></div></div>
  }
  if (!config) return <EmptyState icon="warning" title="Prototype state not mapped" description="This source state is recorded in the catalog but is not yet represented by a visual fixture." action="Open home" onAction={() => navigate({ scene: 'home' })} failure/>
  const advance = () => {
    if (query.scene === 'onboarding' && query.state === 'onboarding') return navigate({ scene: 'onboarding', state: 'git-bash' })
    if (query.scene === 'organization' && ['select', 'join'].includes(query.state)) return navigate({ scene: 'organization', state: 'normal' })
    navigate({ scene: config.next })
  }
  return <div className="onboarding-screen"><div className="onboarding-card"><div className="brand-symbol"><Logo compact/></div><p className="eyebrow">{config.eyebrow}</p><h1>{config.title}</h1><p>{config.text}</p><div className="onboarding-actions"><button className="button primary" onClick={advance}>{config.action}</button><button className="button" onClick={() => navigate({ scene: 'home' })}>Skip demo</button></div><div className="lifecycle-progress"><span className="active"/><span/><span/><span/></div></div></div>
}

export function HomeScene({ onToast }) {
  return <div className="page-scroll"><div className="page-content">
    <PageHeading eyebrow="Home" title="Good morning, workspace admin" description="Continue where you left off or open a built-in app." action={<><span className="status-dot running"/> Connected</>}/>
    <section className="section"><div className="section-header"><h2>Continue working</h2><button className="section-link" onClick={() => navigate({ scene: 'chat' })}>View sessions <Icon name="arrow" size={12}/></button></div>
      <div className="continue-grid">{sessions.slice(0, 3).map((session) => <button key={session.id} className="continue-card" onClick={() => navigate({ scene: 'chat', state: session.id === 'welcome' ? 'normal' : 'detail' })}><span className="app-art"><Icon name="chat" size={17}/></span><span className="card-title"><h3>{session.title}</h3><p>{session.detail}</p><span className="source-line">{session.time}</span></span><Icon name="arrow" size={15}/></button>)}</div>
    </section>
    <section className="section"><div className="section-header"><h2>Built-in apps</h2><button className="section-link" onClick={() => onToast('App installation is mocked in this baseline')}>Manage apps <Icon name="arrow" size={12}/></button></div>
      <div className="built-in-grid">{products.map((product) => <button key={product.id} className="built-in-card" onClick={() => navigate({ scene: product.id === 'assistant' ? 'chat' : product.id === 'browser' ? 'browser' : 'skills' })}><span className={'app-art ' + product.tone}>{product.art}</span><span><h3>{product.name}</h3><p>{product.description}</p></span></button>)}</div>
    </section>
    <section className="section"><div className="section-header"><h2>Workspace health</h2><span className="muted">Updated just now</span></div><div className="card-grid"><div className="surface-card"><p className="eyebrow">Sources</p><h3 className="metric">3 connected</h3><p className="muted">GitHub, Notion, and local files are available.</p></div><div className="surface-card"><p className="eyebrow">Skills</p><h3 className="metric">12 installed</h3><p className="muted">3 skills have updates ready to review.</p></div><div className="surface-card"><p className="eyebrow">Automations</p><h3 className="metric">2 active</h3><p className="muted">The next digest runs tomorrow at 09:00.</p></div></div></section>
  </div></div>
}

function SessionList({ activeId, onNew }) {
  return <aside className="session-sidebar"><button className="new-chat" onClick={onNew}><Icon name="plus" size={15}/> New session <span className="shortcut">⌘ K</span></button><div className="session-label">Recent sessions</div>{sessions.map((session) => <button key={session.id} className={'session-item' + (activeId === session.id ? ' active' : '')} onClick={() => navigate({ scene: 'chat', state: session.id === 'welcome' ? 'normal' : 'detail' })}><strong>{session.title}</strong><small>{session.time}</small></button>)}<div className="session-label">Saved views</div><button className="session-item" onClick={() => navigate({ scene: 'chat', state: 'empty' })}>Flagged</button><button className="session-item" onClick={() => navigate({ scene: 'chat', state: 'archived' })}>Archived</button></aside>
}

export function ChatScene({ query, onToast }) {
  const [message, setMessage] = useState('')
  const [sent, setSent] = useState(false)
  const activeId = query.state === 'detail' ? 'prototype' : 'welcome'
  const empty = query.state === 'empty' || query.state === 'archived'
  const submit = () => { if (!message.trim()) return; setSent(true); setMessage(''); onToast('Message added to the local mock conversation') }
  return <div className="assistant-layout"><SessionList activeId={activeId} onNew={() => { setSent(false); navigate({ scene: 'chat', state: 'normal' }) }}/><main className="assistant-main">
    <header className="assistant-header"><div className="assistant-title"><span className="assistant-orb"><Icon name="spark" size={15}/></span><span>{empty ? (query.state === 'archived' ? 'Archived sessions' : 'Flagged sessions') : 'Welcome to Polo'}</span></div><div className="assistant-context"><span className="context-pill">Polo workspace</span><button className="icon-button" onClick={() => onToast('Session actions are available in the prototype')} aria-label="More session actions"><Icon name="more" size={16}/></button></div></header>
    {empty ? <div className="detail-scroll"><EmptyState icon="chat" title={query.state === 'archived' ? 'No archived sessions' : 'Nothing flagged yet'} description="Saved views update as you work. This state is intentionally quiet so it can be used in visual reviews." action="Start a new session" onAction={() => navigate({ scene: 'chat', state: 'normal' })}/></div> : <><div className="chat-scroll"><div className="message"><div className="message-avatar"><Icon name="spark" size={13}/></div><div className="bubble"><strong>Welcome to Polo.</strong><p>I can help you explore this workspace, draft a plan, or run a permitted action. The prototype keeps this conversation local and deterministic.</p><div className="tool-note"><Icon name="check" size={14}/> Transport connected · mock runtime</div></div></div><div className="message user"><div className="message-avatar">W</div><div className="bubble">Show me the reusable prototype baseline and its available scenes.</div></div><div className="message"><div className="message-avatar"><Icon name="spark" size={13}/></div><div className="bubble"><p>Here are the stable surfaces: lifecycle, workspace shell, sessions, resources, settings, browser, and organization management.</p><div className="chip-row"><button className="chip" onClick={() => navigate({ scene: 'sources' })}>Open resources</button><button className="chip" onClick={() => navigate({ scene: 'settings', state: 'appearance' })}>Review appearance</button></div></div></div>{sent && <div className="message user"><div className="message-avatar">W</div><div className="bubble">The local mock is ready for review.</div></div>}</div><div className="composer-wrap"><div className="composer"><button className="icon-button" onClick={() => onToast('Attachment preview is mocked')} aria-label="Attach file"><Icon name="plus" size={17}/></button><textarea value={message} onChange={(event) => setMessage(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); submit() } }} placeholder="Ask Polo anything about this workspace…" aria-label="Message Polo"/><button className="send-button" onClick={submit} aria-label="Send message"><Icon name="arrow" size={15}/></button></div><div className="composer-hint">Enter to send · Shift + Enter for a new line</div></div></>}
  </main></div>
}

function ResourceList({ kind, selected, onSelect }) {
  const list = kind === 'sources' ? sources : kind === 'skills' ? skills : automations
  return <aside className="resource-nav"><button className="button primary wide-button" onClick={() => onSelect('new')}><Icon name="plus" size={14}/> Add {kind === 'sources' ? 'source' : kind === 'skills' ? 'skill' : 'automation'}</button><div className="filter-box"><Icon name="search" size={14}/><input placeholder="Filter" aria-label="Filter list"/></div>{list.map((item) => <button key={item.id} className={'nav-item list-item' + (selected === item.id ? ' active' : '')} onClick={() => onSelect(item.id)}><span className="list-item-icon">{kind === 'sources' ? <Icon name="book" size={14}/> : kind === 'skills' ? <Icon name="spark" size={14}/> : <Icon name="bolt" size={14}/>}</span><span><strong>{item.name}</strong><small>{kind === 'sources' ? item.type : kind === 'skills' ? item.status : item.kind}</small></span></button>)}</aside>
}

export function ResourcesScene({ kind = 'sources', onToast }) {
  const list = kind === 'sources' ? sources : kind === 'skills' ? skills : automations
  const [selected, setSelected] = useState(list[0]?.id)
  const item = list.find((entry) => entry.id === selected) || list[0]
  const titles = { sources: ['Sources', 'Connect the tools and local context your workspace can use.'], skills: ['Skills', 'Reusable capabilities that can be installed, reviewed, and updated.'], automations: ['Automations', 'Run repeatable workspace actions on a schedule or event.'] }
  const title = titles[kind]
  return <div className="resource-layout"><ResourceList kind={kind} selected={selected} onSelect={(value) => { if (value === 'new') return onToast('Creation flow is mocked; no external connection is made'); setSelected(value) }}/><main className="detail-scroll"><div className="detail-content"><PageHeading eyebrow="Workspace library" title={title[0]} description={title[1]} action={<><Icon name="search" size={13}/> {list.length} items</>}/><div className="detail-card surface-card detail-hero"><div className="hero-icon"><Icon name={kind === 'sources' ? 'book' : kind === 'skills' ? 'spark' : 'bolt'} size={22}/></div><div><p className="eyebrow">{kind === 'sources' ? item.type : kind === 'skills' ? item.badge : item.kind}</p><h2>{item.name}</h2><p>{kind === 'sources' ? item.detail : kind === 'skills' ? item.description : item.rule}</p></div><button className="icon-button" onClick={() => onToast('More actions are mocked')} aria-label="More actions"><Icon name="more" size={17}/></button></div><div className="detail-card surface-card"><h2>{kind === 'automations' ? 'When · If · Then' : kind === 'sources' ? 'Connection' : 'Instructions'}</h2>{kind === 'sources' ? <><div className="field"><label>Status</label><div className="inline-value"><span className="status good">{item.status}</span><span className="muted">Last checked just now</span></div></div><div className="field"><label>Permissions</label><div className="permission-grid"><span>Read workspace context</span><span>Run approved tools</span><span>Receive updates</span></div></div></> : kind === 'skills' ? <><p>This skill is source-backed and can be refreshed from the project baseline. Its instructions remain visible in the reusable mock so design reviews can inspect hierarchy and density.</p><div className="code-block">name: {item.id}<br/>status: {item.status.toLowerCase()}<br/>scope: project</div></> : <><div className="automation-rule"><span className="rule-label">WHEN</span><strong>{item.rule}</strong></div><div className="automation-rule"><span className="rule-label">THEN</span><strong>Run with workspace permissions</strong></div><div className="timeline"><span className="timeline-dot"/><span>Last run succeeded · Yesterday at 09:00</span></div></>}</div><div className="detail-card surface-card"><h2>Activity</h2><div className="activity-row"><span className="status-dot running"/><span>Mock data refreshed</span><small>Just now</small></div><div className="activity-row"><span className="status-dot"/><span>Source contract reviewed</span><small>Yesterday</small></div></div></div></main></div>
}

function SettingsNav({ selected, onSelect }) {
  return <aside className="settings-nav">{settingsGroups.map((group) => <React.Fragment key={group.id}><div className="nav-heading">{group.label}</div>{group.items.map((item) => <button key={item.id} className={'nav-item' + (selected === item.id ? ' active' : '')} onClick={() => onSelect(item.id)}><Icon name={item.id === 'appearance' ? 'sun' : item.id === 'security' ? 'lock' : item.id === 'notifications' ? 'info' : 'settings'} size={14}/><span>{item.label}</span></button>)}</React.Fragment>)}</aside>
}

export function SettingsScene({ query, onToast }) {
  const initial = query.state !== 'normal' && query.state !== 'list' && query.state !== 'detail' ? query.state : 'appearance'
  const [selected, setSelected] = useState(initial)
  const [saved, setSaved] = useState(false)
  const item = settingsGroups.flatMap((group) => group.items).find((entry) => entry.id === selected) || settingsGroups[0].items[0]
  const save = () => { setSaved(true); onToast('Settings saved in local mock state') }
  return <div className="settings-layout"><SettingsNav selected={selected} onSelect={(value) => { setSelected(value); setSaved(false) }}/><main className="detail-scroll"><div className="detail-content"><PageHeading eyebrow="Settings" title={item.label} description={item.description} action={<><Icon name="settings" size={13}/> Local preferences</>}/><div className="detail-card surface-card settings-card"><h2>{item.label}</h2>{selected === 'appearance' ? <><div className="field"><label>Theme</label><select defaultValue={query.theme} onChange={(event) => { const theme = event.target.value; document.documentElement.dataset.theme = theme; navigate({ theme }) }}><option value="light">Light</option><option value="dark">Dark</option></select></div><div className="field"><label>Language</label><select defaultValue={query.lang}><option>简体中文</option><option>English</option><option>日本語</option></select></div><div className="field"><label>Interface density</label><div className="segmented"><button className="selected">Comfortable</button><button>Compact</button></div></div></> : selected === 'notifications' ? <div className="notification-list">{notifications.map((notification) => <div className="notification-row" key={notification.title}><span className="notification-mark"/><span><strong>{notification.title}</strong><p>{notification.body}</p><small>{notification.time}</small></span></div>)}</div> : <><div className="field"><label>Display name</label><input defaultValue={selected === 'workspace' ? 'Polo workspace' : 'Workspace admin'}/></div><div className="field"><label>Description</label><textarea defaultValue={item.description}/></div><div className="field"><label>Behavior</label><div className="toggle-row"><span><strong>Ask before external actions</strong><small>Keep approvals visible in every session.</small></span><button className="toggle on" onClick={() => onToast('Approval behavior toggled')}><i/></button></div></div></>}<div className="settings-form-actions"><button className="button" onClick={() => setSaved(false)}>Reset</button><button className="button primary" onClick={save}>{saved ? 'Saved' : 'Save changes'}</button></div></div></div></main></div>
}

export function BrowserScene({ onToast }) {
  const [url, setUrl] = useState('https://app.polo.local')
  return <div className="browser-view"><div className="browser-toolbar"><button className="icon-button" onClick={() => onToast('Back is mocked')} aria-label="Back"><Icon name="back" size={15}/></button><button className="icon-button" onClick={() => onToast('Forward is mocked')} aria-label="Forward"><Icon name="arrow" size={15}/></button><button className="icon-button" onClick={() => onToast('Page reloaded')} aria-label="Reload"><Icon name="refresh" size={15}/></button><div className="address-bar"><Icon name="lock" size={13}/><input value={url} onChange={(event) => setUrl(event.target.value)} aria-label="Address"/></div><button className="icon-button" onClick={() => onToast('External webview is intentionally local-only')} aria-label="Open externally"><Icon name="external" size={15}/></button></div><div className="browser-empty"><div className="browser-illustration"><Icon name="monitor" size={29}/></div><h1>Local browser surface</h1><p>This is a static representation of Electron’s WebAppView and browser toolbar. No remote page is loaded in the reusable baseline.</p><div className="onboarding-actions"><button className="button primary" onClick={() => onToast('Browser navigation is mocked')}>Load mock page</button><button className="button" onClick={() => navigate({ scene: 'home' })}>Back to Home</button></div><span className="approximation-note"><Icon name="info" size={13}/> Boundary: native webview / BrowserView intentionally approximated</span></div></div>
}

export function OrganizationScene({ query, onToast }) {
  const [tab, setTab] = useState(query.state === 'members' ? 'members' : 'overview')
  return <div className="organization-layout"><aside className="settings-nav"><div className="org-profile"><span className="space-avatar">P</span><div><strong>Creator Space</strong><small>polo.local</small></div></div><button className={'nav-item' + (tab === 'overview' ? ' active' : '')} onClick={() => setTab('overview')}><Icon name="grid" size={14}/> Overview</button><button className={'nav-item' + (tab === 'members' ? ' active' : '')} onClick={() => setTab('members')}><Icon name="users" size={14}/> Members</button><button className={'nav-item' + (tab === 'artifacts' ? ' active' : '')} onClick={() => setTab('artifacts')}><Icon name="spark" size={14}/> Creator artifacts</button></aside><main className="detail-scroll"><div className="detail-content"><PageHeading eyebrow="Organization" title={tab === 'members' ? 'Members' : tab === 'artifacts' ? 'Creator artifacts' : 'Creator Space'} description="Manage shared access and the artifacts published by this organization." action={<button className="button" onClick={() => onToast('Invite flow is mocked')}>Invite member</button>}/><div className="detail-card surface-card"><h2>{tab === 'members' ? 'People with access' : tab === 'artifacts' ? 'Published artifacts' : 'Organization health'}</h2>{tab === 'members' ? <div className="member-list"><div><span className="space-avatar">W</span><span><strong>Workspace admin</strong><small>Owner · admin@polo.local</small></span><span className="status good">Active</span></div><div><span className="space-avatar">A</span><span><strong>Alex Chen</strong><small>Member · alex@polo.local</small></span><span className="status neutral">Member</span></div></div> : tab === 'artifacts' ? <div className="artifact-list"><div><span className="app-art"><Icon name="spark" size={16}/></span><span><strong>Frontend Prototype</strong><small>Skill · v0.4.2 · Published yesterday</small></span><button className="button" onClick={() => onToast('Artifact details opened')}>View</button></div><div><span className="app-art teal"><Icon name="grid" size={16}/></span><span><strong>Workspace Hub</strong><small>Web App · v1.2 · Draft</small></span><button className="button" onClick={() => onToast('Draft editor is mocked')}>Review</button></div></div> : <div className="org-stats"><div><strong>2</strong><small>Members</small></div><div><strong>4</strong><small>Published artifacts</small></div><div><strong>99.9%</strong><small>Transport uptime</small></div></div>}</div><div className="detail-card surface-card"><h2>Access policy</h2><div className="toggle-row"><span><strong>Require approval for new members</strong><small>Owners review invitations before access is granted.</small></span><button className="toggle on" onClick={() => onToast('Policy toggled')}><i/></button></div></div></div></main></div>
}

export function NotificationsScene() {
  return <div className="page-scroll"><div className="page-content"><PageHeading eyebrow="Inbox" title="Notifications" description="Updates from your workspace, sources, and automations."/><div className="surface-card"><div className="notification-list">{notifications.map((item) => <div className="notification-row" key={item.title}><span className="notification-mark"/><span><strong>{item.title}</strong><p>{item.body}</p><small>{item.time}</small></span></div>)}</div></div></div></div>
}

export function ShortcutsScene() {
  const shortcuts = [['Open command menu', '⌘ K'], ['New session', '⌘ N'], ['Toggle navigator', '⌘ B'], ['Search workspace', '⌘ /'], ['Open settings', '⌘ ,']]
  return <div className="page-scroll"><div className="page-content"><PageHeading eyebrow="System" title="Keyboard shortcuts" description="The commands used by the Electron renderer shell."/><div className="surface-card shortcuts-list">{shortcuts.map(([label, key]) => <div key={label}><span>{label}</span><kbd>{key}</kbd></div>)}</div></div></div>
}
