#!/usr/bin/env python3
"""Outside-in counterexamples: same object, retained state, no implicit grants."""
from pathlib import Path
import json,hashlib,os
from playwright.sync_api import sync_playwright
R=Path(__file__).resolve().parents[3];B=R/'docs/mvp-complete-flow-hifi';A=R/'design-demos/polo-client-source-baseline';E=B/os.environ.get('POLO_REVIEW_EVIDENCE','evidence/r15-closure');E.mkdir(parents=True,exist_ok=True)
M=json.loads((B/'prototype-manifest.json').read_text());by={s['id']:s for s in M['scenes']}
report={'revision':M['revision'],'artifacts':{str(p.relative_to(R)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [B/'prototype-manifest.json',B/'prototype.html',B/'review.html',A/'prototype.html']},'checks':[],'errors':[]}
def ck(name,ok,detail=''):
 report['checks'].append({'name':name,'passed':bool(ok),'detail':detail})
 if not ok:print('FAIL',name,detail,flush=True)
with sync_playwright() as p:
 browser=p.chromium.launch()
 def new(sid):
  page=browser.new_page(viewport={'width':1500,'height':1000});page.set_default_timeout(6000);page.set_default_navigation_timeout(30000);page.on('pageerror',lambda e:report['errors'].append(str(e)));page.goto((B/'review.html').as_uri()+'#scene='+sid);page.wait_for_timeout(250);return page
 def frame(page):return page.locator('[data-assistant-viewport]' if by[page.evaluate('document.body.dataset.currentScene')]['surface']=='assistant' else '[data-prototype-viewport]').element_handle().content_frame()
 def active(page):return frame(page).locator('[data-prototype-scene]:visible')
 def click(page,name):active(page).get_by_role('button',name=name,exact=True).first.click();page.wait_for_timeout(130)
 def go(page,sid):page.evaluate('(s)=>location.hash="scene="+s',sid);page.wait_for_function('(s)=>document.body.dataset.currentScene===s',arg=sid);frame(page).wait_for_function('(s)=>document.body.dataset.currentScene===s',arg=sid)
 for scope in ['personal','enterprise']:
  page=new('A-'+scope+'-restricted');click(page,'首页');click(page,'管理技能');ck(scope+' revoked source survives home return','最后一个有效来源已失效' in active(page).inner_text())
  ck(scope+' revoked skill cannot enable',active(page).get_by_role('button',name='为我启用',exact=True).count()==0)
  page.close();page=new('A-'+scope+'-detail');click(page,'查看内置技能');click(page,'停用内置技能');click(page,'首页');click(page,'管理技能');click(page,'查看内置技能');ck(scope+' same-name builtin remains disabled',active(page).get_by_role('button',name='启用内置技能',exact=True).is_visible());click(page,'查看来源技能');ck(scope+' source skill unaffected','已启用' in frame(page).locator('.polo-skill-detail').inner_text());page.close()
 for origin in ['P-M10-MENU','P-M10-MENU-ENT']:
  for role in ['创作者工作台','企业管理后台']:
   page=new(origin);active(page).get_by_role('button',name=role).first.click();page.wait_for_timeout(150);txt=active(page).inner_text();ck(origin+' '+role+' correct target',('创作者工作台' in txt and '北方贸易' not in txt) if role=='创作者工作台' else '北方贸易' in txt)
   click(page,'取消');ck(origin+' '+role+' cancel retains origin',page.evaluate('document.body.dataset.currentScene')==origin);page.close()
 for first,second in [('design','growth'),('growth','design')]:
  page=new('P-M07-DETAIL-'+('PAID' if first=='design' else 'FOCUS')+'-SUBSCRIPTION');click(page,'退出圈子');click(page,'确认退出');click(page,'首页')
  key='brand' if first=='design' else 'growth';button=active(page).locator('[data-app-key="'+key+'"] button').first;ck(first+' sole-source app blocked after leave',button.is_disabled());ck(first+' shared app remains enabled',not active(page).locator('[data-app-key="meeting"] button').first.is_disabled())
  click(page,'我的圈子');row=active(page).locator('[data-circle-kind="'+second+'"]');row.get_by_role('button',name='查看详情',exact=True).click();page.wait_for_timeout(130);click(page,'订阅');click(page,'退出圈子');click(page,'确认退出');click(page,'首页');ck(first+' then '+second+' last source blocks shared app',active(page).locator('[data-app-key="meeting"] button').first.is_disabled());page.close()
 page=new('P-M04-RUNTIME-PERSONAL');click(page,'停止');click(page,'后台任务');txt=active(page).locator('.runtime-row').first.inner_text();ck('stopped report stays stopped in runtime','已停止' in txt and '运行中' not in txt,txt);page.close()
 for sid in ['P-M11-OFFLINE-HOME','P-M03-HOME-OFFLINE']:
  page=new(sid);ck(sid+' no new app startup',active(page).locator('[data-app-key="brand"] button').first.is_disabled());ck(sid+' no new assistant startup',active(page).get_by_role('button',name='打开助手',exact=True).is_disabled());click(page,'重试连接');ck(sid+' reconnect returns eligibility only',page.evaluate('document.body.dataset.currentScene')=='P-M03-HOME-PERSONAL');ck(sid+' verified catalog allows explicit open',not active(page).locator('[data-app-key="brand"] button').first.is_disabled());page.close()
 for sid,name in [('P-M11-CONTRACT','稍后处理'),('P-M11-CONTRACT-DL','返回升级提示'),('P-M11-CONTRACT-FAIL','返回升级提示')]:
  page=new(sid);click(page,name);ck(sid+' cancellation remains gated',page.evaluate('document.body.dataset.currentScene')=='P-M11-CONTRACT');ck(sid+' no personal downgrade','个人空间不受影响' not in active(page).inner_text());page.close()
 # Change perspective: leave through a different consumer, then return to the same object.
 for scope in ['personal','enterprise']:
  page=new('A-'+scope+'-detail');click(page,'卸载本机副本');click(page,'取消');ck(scope+' uninstall cancellation retains installed version','就绪' in frame(page).locator('.polo-skill-detail').inner_text());page.close()
 page=new('P-M07-DETAIL-PAID-SUBSCRIPTION');click(page,'退出圈子');click(page,'取消');click(page,'首页');ck('cancel circle exit leaves sole-source app usable',not active(page).locator('[data-app-key="brand"] button').first.is_disabled());page.close()
 page=new('P-M07-DETAIL-PAID-SUBSCRIPTION');click(page,'退出圈子');click(page,'确认退出');click(page,'首页');click(page,'我的圈子');active(page).locator('[data-circle-kind="growth"]').get_by_role('button',name='查看详情',exact=True).click();page.wait_for_timeout(100);click(page,'订阅');click(page,'退出圈子');click(page,'确认退出');click(page,'首页');click(page,'管理技能');ck('last circle source also revokes assistant skill','最后一个有效来源已失效' in active(page).inner_text());page.close()
 for origin,target in [('P-M02-CONFIRM-PERSONAL','P-M03-HOME-ENT'),('P-M02-CONFIRM','P-M03-HOME-PERSONAL')]:
  page=new(origin);click(page,'停止全部并切换');ck(origin+' enters stop progress','STOPPING' in page.evaluate('document.body.dataset.currentScene'));page.wait_for_function('(s)=>document.body.dataset.currentScene===s',arg=target);ck(origin+' commits only after progress',page.evaluate('document.body.dataset.currentScene')==target);page.close()
 page=new('P-M02-STOP-FAILED');click(page,'取消切换');click(page,'返回首页');click(page,'后台任务');txt=active(page).locator('.runtime-row').first.inner_text();ck('partial stop cancellation never revives quote','已停止' in txt and '运行中' not in txt,txt);page.close()
 page=new('P-M11-CONTRACT-READY');click(page,'进入我的空间');ck('upgrade verified result has safe entry',page.evaluate('document.body.dataset.currentScene')=='P-M03-HOME-PERSONAL');page.close()

 # Independently found cross-surface and identity counterexamples.
 page=new('P-M11-OFFLINE-HOME');click(page,'管理技能');click(page,'打开 Polo 助手');active(page).get_by_role('textbox',name='消息',exact=True).fill('离线任务不应运行');ck('offline via skills still blocks send',active(page).locator('button[type=submit]').is_disabled());page.close()
 for scope in ['personal','enterprise']:
  page=new('A-'+scope+'-preferences');click(page,'回答偏好');active(page).get_by_label('助手如何称呼你').fill('待保存称呼');page.once('dialog',lambda d:d.dismiss());click(page,'返回助手');ck(scope+' preferences cancel stays with input',page.evaluate('document.body.dataset.currentScene')=='A-'+scope+'-preferences' and active(page).get_by_label('助手如何称呼你').input_value()=='待保存称呼');page.once('dialog',lambda d:d.accept());click(page,'返回助手');ck(scope+' preferences explicit discard leaves',page.evaluate('document.body.dataset.currentScene')!='A-'+scope+'-preferences');page.close()
 for key,scope in [('report','personal'),('contract','enterprise')]:
  page=new('P-M04-APP-'+key.upper());click(page,'关闭标签');ck(key+' running close has choice',page.evaluate('document.body.dataset.currentScene')=='P-M04-CLOSE-'+key.upper());click(page,'取消');click(page,'关闭标签');click(page,'停止并关闭');click(page,'后台任务');rows=active(page).locator('[data-task-key="'+key+'"]');ck(key+' stop close retains same object stopped','已停止' in rows.first.inner_text());page.close()
 # Actual file transfer, no fixture pretending an import occurred.
 for scope in ['personal','enterprise']:
  page=new('A-'+scope+'-files');click(page,'导出允许内容')
  with page.expect_download() as dl:click(page,'下载允许内容')
  exported=json.loads(Path(dl.value.path()).read_text());ck(scope+' export excludes credentials and references',set(exported)=={'format','title','messages'} and len(exported['messages'])==2 and all(set(m)=={'role','text'} for m in exported['messages']))
  page.close();page=new('A-'+scope+'-files');click(page,'导入对话内容');picker=active(page).get_by_label('选择导出文件');picker.set_input_files({'name':'broken.json','mimeType':'application/json','buffer':b'bad'});page.wait_for_timeout(100);ck(scope+' invalid import creates no result','未导入任何内容' in active(page).inner_text())
  data={'format':'polo-conversation-content-v1','title':'同名材料','credentials':'must-not-transfer','messages':[{'role':'user','text':'选择的第二份材料','source':'forbidden'},{'role':'assistant','text':'第二份材料的结论'}]}
  picker.set_input_files({'name':'second.json','mimeType':'application/json','buffer':json.dumps(data,ensure_ascii=False).encode()});page.wait_for_timeout(180);ck(scope+' import previews selected content','选择的第二份材料' in active(page).inner_text());click(page,'取消导入');ck(scope+' cancel import keeps original conversation','选择的第二份材料' not in active(page).inner_text());click(page,'查看会话文件');click(page,'导入对话内容');active(page).get_by_label('选择导出文件').set_input_files({'name':'second.json','mimeType':'application/json','buffer':json.dumps(data,ensure_ascii=False).encode()});page.wait_for_timeout(180);click(page,'确认导入');ck(scope+' import creates new nonrunning object','包含 2 条消息' in active(page).inner_text() and '没有自动执行' in active(page).inner_text());click(page,'打开导入对话');ck(scope+' result belongs to selected file','选择的第二份材料' in active(page).inner_text() and '请整理这份资料' not in active(page).inner_text());page.close()


 # Revisit independently discovered cases through ordinary consumers.
 page=new('P-M11-REVOKE');click(page,'回到空间切换');ck('revoked enterprise absent from usable targets',active(page).locator('[data-go="P-M02-CONFIRM-PERSONAL"]').is_disabled());click(page,'返回 Polo 首页');ck('revocation recovers into personal space',page.evaluate('document.body.dataset.currentScene')=='P-M03-HOME-PERSONAL');page.close()
 page=new('P-M07-RENEW-RETURN');click(page,'查询原订单和资格');click(page,'返回我的圈子');card=active(page).locator('[data-circle-kind="design"]');ck('renewal result reaches everyday list','2026-12-02' in card.inner_text());card.get_by_role('button',name='查看详情',exact=True).click();page.wait_for_timeout(150);ck('renewed detail is circle content',page.evaluate('document.body.dataset.currentScene')=='P-M07-DETAIL-PAID');click(page,'首页');click(page,'我的圈子');ck('renewal survives home roundtrip','2026-12-02' in active(page).locator('[data-circle-kind="design"]').inner_text());page.close()
 page=new('P-M07-DETAIL-PAID-SUBSCRIPTION');click(page,'退出圈子');click(page,'确认退出');click(page,'重新加入圈子');ck('rejoin opens browser without granting membership',page.evaluate('document.body.dataset.currentScene')=='P-M07-REJOIN-BROWSER');page.close()
 page=new('P-M07-DETAIL-PAID-SUBSCRIPTION');click(page,'退出圈子');click(page,'确认退出');click(page,'首页');click(page,'我的圈子');active(page).locator('[data-circle-kind="growth"]').get_by_role('button',name='查看详情',exact=True).click();page.wait_for_timeout(150);click(page,'订阅');click(page,'退出圈子');ck('last-source confirmation uses current facts','将失去最后一个有效来源' in active(page).inner_text());click(page,'确认退出');ck('last-source result uses current facts','已没有有效来源' in active(page).inner_text() and '授权仍然有效' not in active(page).inner_text());page.close()
 page=new('P-M09-APP-BANNER');ck('App insufficient credit stops AI request','当前 AI 请求已停止' in active(page).inner_text());click(page,'通知所有者');ck('App notify stays with contract',page.evaluate('document.body.dataset.currentScene')=='P-M09-APP-NOTIFIED' and '合同审查' in active(page).inner_text());click(page,'首页');active(page).locator('[data-app-key="contract"] button').click();page.wait_for_timeout(150);ck('App credit block survives reopening','企业积分不足' in active(page).inner_text());click(page,'首页');click(page,'管理技能');click(page,'打开 Polo 助手');active(page).get_by_role('textbox',name='消息',exact=True).fill('不能绕过企业积分不足');ck('App credit block follows assistant consumer',active(page).locator('button[type=submit]').is_disabled());page.close()
 page=new('A-personal-files')
 for num in [1,2]:
  click(page,'导入对话内容');data={'format':'polo-conversation-content-v1','title':'同名材料','messages':[{'role':'user','text':'不同对象'+str(num)}]};active(page).get_by_label('选择导出文件').set_input_files({'name':'same.json','mimeType':'application/json','buffer':json.dumps(data,ensure_ascii=False).encode()});page.wait_for_timeout(150);click(page,'确认导入');click(page,'打开导入对话');click(page,'查看会话文件')
 click(page,'回到原对话');click(page,'首页');click(page,'打开助手');ck('opening new assistant does not reuse imported object',not frame(page).locator('.mvp-chat-column').get_by_text('不同对象2',exact=True).count())
 for num in [1,2]:
  click(page,'打开导入对话：同名材料 · 不同对象'+str(num));txt=frame(page).locator('.mvp-chat-column').inner_text();ck('same-name imported object '+str(num)+' remains recoverable','不同对象'+str(num) in txt and '不同对象'+str(3-num) not in txt)
 page.close()


 page=new('P-M10-MENU-NOPRIV');active(page).locator('[data-go^="P-M10-SETTINGS"]').first.click();page.wait_for_timeout(150);ck('unqualified settings preserve account facts','尚无创作者资格' in active(page).inner_text() and '有效创作者' not in active(page).inner_text());ck('unqualified settings offer no management handoff',active(page).locator('[data-go*="CREATOR-BROWSER"]:visible,[data-go*="ADMIN-BROWSER"]:visible').count()==0);page.close()
 page=new('P-M01-CREATE-ENT');click(page,'打开企业管理后台');ck('create opens browser without changing space',page.evaluate('document.body.dataset.currentScene')=='P-M01-CREATE-BROWSER');click(page,'返回 Polo');ck('create return requires explicit query',page.evaluate('document.body.dataset.currentScene')=='P-M01-CREATE-RETURN');click(page,'查询创建结果');ck('created enterprise binds owner before entry','唯一所有者' in active(page).inner_text() and '当前仍在我的空间' in active(page).inner_text());click(page,'进入晨星科技');ck('explicit entry consumes verified owner',active(page).locator('#space-type').inner_text()=='企业空间 · 所有者');page.close()
 for sid in ['P-M01-CREATE-PENDING','P-M01-CREATE-QUERY-FAILED']:
  page=new(sid);click(page,'留在我的空间');ck(sid+' safe recovery',page.evaluate('document.body.dataset.currentScene')=='P-M03-HOME-PERSONAL');page.close()
 page=new('P-M07-EXPIRED');click(page,'返回我的圈子');card=active(page).locator('[data-circle-kind="design"]');ck('expired relation retains its actual expiry','2026-09-01' in card.inner_text() and '已到期' in card.inner_text());active(page).get_by_label('圈子状态').select_option('restore');ck('expired relation appears in recovery filter',card.is_visible());active(page).get_by_label('圈子状态').select_option('all');ck('expired relation survives filter roundtrip',card.is_visible());card.get_by_role('button',name='查看详情',exact=True).click();page.wait_for_timeout(150);ck('expired relation opens expired detail',page.evaluate('document.body.dataset.currentScene')=='P-M07-EXPIRED');page.close()
 page=new('P-M07-DETAIL-PAID-AFTER-LEAVE');click(page,'重新加入圈子');click(page,'取消本次前往');ck('cancel rejoin preserves exited state',page.evaluate('document.body.dataset.currentScene')=='P-M07-DETAIL-PAID-AFTER-LEAVE' and '已退出' in active(page).inner_text());page.close()
 for sid in ['P-M03-INSPECTOR','P-M03-INSPECTOR-PERSONAL','P-M11-BLOCKED-WITHDRAWN','P-M11-BLOCKED-VERSION','P-M11-OFFLINE-RUNNING']:
  page=new(sid);txt=active(page).inner_text();ck(sid+' App content responsibility is explicit','可随时查看' not in txt and '结果保留' not in txt and ('应用' in txt));page.close()
 page=new('A-personal-transfer-import');page.locator('[data-viewport-select]').select_option('desktop-800x600',force=True);data={'format':'polo-conversation-content-v1','messages':[{'role':'user','text':'x'*10000}]};active(page).get_by_label('选择导出文件').set_input_files({'name':'long.json','mimeType':'application/json','buffer':json.dumps(data).encode()});page.wait_for_timeout(200);sizes=active(page).locator('.polo-transfer li').evaluate('(e)=>[e.scrollWidth,e.clientWidth]');ck('valid long transfer content stays readable',sizes[0]<=sizes[1]+1,str(sizes));click(page,'取消导入');ck('long import cancellation leaves no object','x'*30 not in frame(page).locator('.mvp-chat-column').inner_text());page.close()

 # Recheck newly discovered result dates, identities, roles and actual cancellation progress.
 page=new('P-M07-EXPIRED')
 for label in ['续费恢复','去浏览器支付','返回 Polo','查询原订单和资格','订阅']:click(page,label)
 ck('expired purchase updates all entitlement consumers','2026-11-02' in active(page).inner_text() and '2026-09-01' not in active(page).inner_text());click(page,'返回我的圈子');ck('expired purchase also updates everyday list','2026-11-02' in active(page).locator('[data-circle-kind="design"]').inner_text());page.close()
 for sid in ['P-M07-EXPIRED','P-M07-DETAIL-PAID-AFTER-LEAVE','P-M07-RENEW','P-M07-RENEW-EXPIRED','P-M07-LEAVE','P-M07-LEAVE-PAID']:
  page=new(sid);ck(sid+' same skill identity','增长案例检索' not in active(page).inner_text() and '资料研究' in active(page).inner_text());page.close()
 for delay in [0,420,820]:
  page=new('P-M02-CONFIRM');active(page).get_by_role('button',name='停止全部并切换',exact=True).click();page.wait_for_timeout(delay);active(page).get_by_role('button',name='取消切换',exact=True).click();page.wait_for_timeout(180);txt=active(page).inner_text();ck('cancel at '+str(delay)+' has no fabricated failure','失败' not in active(page).locator('.dialog-list').inner_text());observed=frame(page).evaluate("['quote','contract'].filter(k=>window.poloTaskStopped('enterprise',k)).length");count=active(page).locator('.switch-progress-summary span strong').inner_text();ck('cancel at '+str(delay)+' count follows actual stopped objects',count.startswith(str(observed)+' /'),str((count,observed)));page.wait_for_timeout(1800);ck('cancel at '+str(delay)+' invalidates delayed switch',page.evaluate('document.body.dataset.currentScene')=='P-M02-STOP-CANCEL');page.close()
 page=new('P-M02-STOP-FAILED');click(page,'取消切换');ck('confirmed stop failure remains factual after cancellation','失败' in active(page).locator('.dialog-list').inner_text() and '2 / 3' in active(page).inner_text());page.close()
 for sid in ['P-M10-MENU-ENT','P-M10-MENU-NOPRIV']:
  page=new(sid);ck(sid+' lacks current-enterprise finance entry',active(page).locator('[data-go="P-M09-BROWSER-MENU-ENT"]:visible').count()==0);page.close()
 page=new('P-M01-CREATE-READY');click(page,'进入晨星科技');active(page).locator('[data-go="P-M10-MENU-ENT"]').first.click();page.wait_for_timeout(150);ck('verified enterprise owner has financial handoff',active(page).locator('[data-go="P-M09-BROWSER-MENU-ENT"]').is_visible());ck('owner account menu agrees with verified role','晨星科技 · 所有者' in active(page).locator('#account-menu .menu-section-title').first.inner_text());active(page).locator('[data-go="P-M09-BROWSER-MENU-ENT"]').click();page.wait_for_timeout(150);ck('owner handoff binds current enterprise','晨星科技 · 所有者' in active(page).inner_text());click(page,'返回 Polo');ck('finance return retains original menu',page.evaluate('document.body.dataset.currentScene')=='P-M10-MENU-ENT');page.close()
 for cause,caption in [('PAUSED','企业已暂停'),('CLOSING','企业关闭处理中'),('ARREARS','企业因欠费受限')]:
  for role in ['MEMBER','MANAGER','OWNER']:
   sid='P-M11-GOVERNANCE-'+cause+'-'+role;page=new(sid);ck(sid+' preserves governance cause',caption in active(page).inner_text());ck(sid+' role controls Browser responsibility',active(page).get_by_role('button',name='在浏览器处理企业限制',exact=True).count()==(1 if role=='OWNER' else 0));
   if role=='OWNER':click(page,'在浏览器处理企业限制');ck(sid+' Browser retains target and cause','晨星科技' in active(page).inner_text() and caption in active(page).inner_text());click(page,'取消本次前往');ck(sid+' cancel keeps restriction',bool(frame(page).evaluate('window.poloEnterpriseGovernance')))
   else:click(page,'联系企业所有者');ck(sid+' contact shares only relevant problem',caption in active(page).get_by_label('可提供的问题信息').input_value() and '账单' not in active(page).inner_text());click(page,'返回限制说明')
   click(page,'返回我的空间');click(page,'切换空间当前：我的空间') if active(page).get_by_role('button',name='切换空间当前：我的空间',exact=True).is_visible() else active(page).locator('[data-go="P-M10-MENU"]').first.click();page.wait_for_timeout(130)
   if page.evaluate('document.body.dataset.currentScene')=='P-M10-MENU':active(page).locator('[data-go="P-M02-SWITCHER-PERSONAL"]').first.click();page.wait_for_timeout(130)
   ck(sid+' safe return cannot bypass enterprise restriction',active(page).locator('[data-go="P-M02-CONFIRM-PERSONAL"]').is_disabled());page.close()
 page=new('P-M11-GOVERNANCE-ARREARS-OWNER');click(page,'在浏览器处理企业限制');click(page,'返回 Polo');ck('governance Browser return remains blocked',bool(frame(page).evaluate('window.poloEnterpriseGovernance')));click(page,'查询企业状态');ck('verified governance result clears only governance',frame(page).evaluate('window.poloEnterpriseGovernance') is None);click(page,'进入晨星科技');click(page,'后台任务');ck('governance recovery does not restart stopped App tasks','已停止' in active(page).locator('[data-task-key="quote"]').first.inner_text());page.close()
 for sid in ['P-M11-GOVERNANCE-PENDING','P-M11-GOVERNANCE-FAILED']:
  page=new(sid);ck(sid+' unknown result remains blocked',bool(frame(page).evaluate('window.poloEnterpriseGovernance')));click(page,'返回我的空间');ck(sid+' safe personal recovery',page.evaluate('document.body.dataset.currentScene')=='P-M03-HOME-PERSONAL');page.close()
 page=new('P-M11-REVOKE');go(page,'P-M11-GOVERNANCE-PAUSED-OWNER');click(page,'重新核对企业状态');click(page,'查询企业状态');ck('governance recovery never restores revoked membership',active(page).get_by_role('button',name='进入晨星科技',exact=True).is_disabled());page.close()

 # Failure discovery from the other direction and an uncorrelated stop status.
 for scope in ['personal','enterprise']:
  for drop in ['request','ack']:
   page=browser.new_page(viewport={'width':1500,'height':1000});page.set_default_timeout(8000);page.set_default_navigation_timeout(30000)
   condition="e.data?.payload?.kind==='stop-assistant-scope'" if drop=='request' else "e.data?.payload?.kind==='assistant-activity'&&e.data?.payload?.request"
   page.add_init_script("window.__dropStopEvidence=true;window.addEventListener('message',e=>{if(window.__dropStopEvidence&&e.data?.type==='product-ui-prototype:peer'&&("+condition+"))e.stopImmediatePropagation()},true)")
   page.goto((B/'review.html').as_uri()+'#scene=A-'+scope+'-new');page.wait_for_timeout(250);active(page).get_by_role('textbox',name='消息',exact=True).fill('原会话停止确认 '+scope+' '+drop);click(page,'发送消息');click(page,'首页')
   menu='P-M10-MENU' if scope=='personal' else 'P-M10-MENU-ENT';switcher='P-M02-SWITCHER-PERSONAL' if scope=='personal' else 'P-M02-SWITCHER';confirm='P-M02-CONFIRM-PERSONAL' if scope=='personal' else 'P-M02-CONFIRM'
   for dest in [menu,switcher,confirm]:active(page).locator('[data-go="'+dest+'"]').first.click();page.wait_for_timeout(130)
   click(page,'停止全部并切换');page.wait_for_timeout(600);row=active(page).locator('[data-assistant-switch-row]');ck(scope+' '+drop+' assistant not stopped before confirmation',row.is_visible() and '已停止' not in row.locator('.row-state').inner_text());failed='P-M02-STOP-FAILED-PERSONAL' if scope=='personal' else 'P-M02-STOP-FAILED';page.wait_for_function('(s)=>document.body.dataset.currentScene===s',arg=failed,timeout=12000);page.wait_for_timeout(150);row=active(page).locator('[data-assistant-switch-row]');ck(scope+' '+drop+' missing confirmation keeps assistant visible',row.is_visible() and '未确认停止' in row.inner_text());key='report' if scope=='personal' else 'quote';ck(scope+' '+drop+' confirmed App stop remains separate','已停止' in active(page).locator('.dialog-list [data-task-key="'+key+'"]').inner_text())
   # Restore delivery only for the explicit user retry; no background success action.
   for child in page.frames:child.evaluate('window.__dropStopEvidence=false')
   click(page,'重试失败项');target='P-M03-HOME-ENT' if scope=='personal' else 'P-M03-HOME-PERSONAL';page.wait_for_function('(s)=>document.body.dataset.currentScene===s',arg=target,timeout=10000);ck(scope+' '+drop+' explicit retry commits verified target',page.evaluate('document.body.dataset.currentScene')==target);page.close()
 page=browser.new_page(viewport={'width':1500,'height':1000});page.set_default_navigation_timeout(30000);page.add_init_script("window.addEventListener('message',e=>{if(e.data?.type==='product-ui-prototype:peer'&&e.data?.payload?.kind==='assistant-activity'&&e.data?.payload?.request)e.stopImmediatePropagation()},true)");page.goto((B/'review.html').as_uri()+'#scene=A-enterprise-new');page.wait_for_timeout(250);active(page).get_by_role('textbox',name='消息',exact=True).fill('取消等待中的停止确认');click(page,'发送消息');click(page,'首页')
 for dest in ['P-M10-MENU-ENT','P-M02-SWITCHER','P-M02-CONFIRM']:active(page).locator('[data-go="'+dest+'"]').first.click();page.wait_for_timeout(130)
 click(page,'停止全部并切换');page.wait_for_timeout(1250);click(page,'取消切换');txt=active(page).locator('.dialog-list').inner_text();ck('cancel after stop request retains unknown confirmation','等待停止确认' in txt and '失败' not in txt);page.wait_for_timeout(2200);ck('cancel with missing confirmation never commits target',page.evaluate('document.body.dataset.currentScene')=='P-M02-STOP-CANCEL');page.close()

 # Repeat a financial action with the latest entitlement, then query its own order.
 page=new('P-M07-DETAIL-PAID-SUBSCRIPTION')
 def renewal_result():
  for label in ['去浏览器支付','返回 Polo','查询原订单和资格']:click(page,label)
 def renewal_subscription():
  click(page,'返回我的圈子');active(page).locator('[data-circle-kind="design"]').get_by_role('button',name='查看详情',exact=True).click();page.wait_for_timeout(130);click(page,'订阅')
 click(page,'续费');ck('first renewal consumes current period','2026-11-02 至 2026-12-02' in active(page).locator('.dialog').inner_text());renewal_result();first_order=active(page).locator('[data-renewal-order]').inner_text();ck('first renewal current entitlement','2026-12-02'==active(page).locator('[data-renewal-result-expiry]').inner_text());click(page,'查看原订单');click(page,'查询原订单和资格');ck('same paid order query is idempotent',active(page).locator('[data-renewal-order]').inner_text()==first_order and active(page).locator('[data-renewal-result-expiry]').inner_text()=='2026-12-02');renewal_subscription()
 click(page,'续费');ck('second renewal uses latest verified entitlement','2026-12-02 至 2027-01-02' in active(page).locator('.dialog').inner_text());click(page,'取消');click(page,'订阅');ck('cancel second quote preserves purchased rights','2026-12-02' in active(page).inner_text());click(page,'续费');click(page,'去浏览器支付');ck('second browser handoff consumes same new quote','2026-12-02 至 2027-01-02' in active(page).inner_text());click(page,'取消本次前往');click(page,'订阅');ck('cancel browser handoff leaves entitlement unchanged','2026-12-02' in active(page).inner_text());click(page,'续费');renewal_result();second_order=active(page).locator('[data-renewal-order]').inner_text();ck('second order is distinct and updates same circle',second_order!=first_order and active(page).locator('[data-renewal-result-expiry]').inner_text()=='2027-01-02');click(page,'查看原订单');ck('original second order retained on return',active(page).locator('[data-renewal-order]').inner_text()==second_order);click(page,'查询原订单和资格');ck('rechecking second order does not purchase another month',active(page).locator('[data-renewal-result-expiry]').inner_text()=='2027-01-02');renewal_subscription();ck('second entitlement reaches ordinary subscription','2027-01-02' in active(page).inner_text())
 for end in ['2027-02-02','2027-03-02','2027-04-02','2027-05-02','2027-06-02','2027-07-02','2027-08-02','2027-09-02','2027-10-02']:
  click(page,'续费');renewal_result();ck('authoritative monthly quote remains bound through '+end,active(page).locator('[data-renewal-result-expiry]').inner_text()==end);renewal_subscription()
 click(page,'续费');ck('monthly limit blocks new payment',active(page).get_by_role('button',name='去浏览器支付',exact=True).is_disabled());click(page,'查看续费限制');click(page,'查看原订单');last_order=active(page).locator('[data-renewal-order]').inner_text();click(page,'查询原订单和资格');ck('limit preserves original last order and entitlement',active(page).locator('[data-renewal-order]').inner_text()==last_order and active(page).locator('[data-renewal-result-expiry]').inner_text()=='2027-10-02');page.close()
 page=new('P-M07-EXPIRED')
 for label in ['续费恢复','去浏览器支付','返回 Polo','查询原订单和资格','续费']:click(page,label)
 ck('restored membership next quote uses restored expiry','2026-11-02 至 2026-12-02' in active(page).locator('.dialog').inner_text());page.close()
 page=new('P-M07-RENEW-YEAR')
 for label in ['前往年度圈续费网页','返回 Polo','查询年度权益','返回我的圈子']:click(page,label)
 active(page).locator('[data-circle-kind="annual"]').get_by_role('button',name='查看详情',exact=True).click();page.wait_for_timeout(130);ck('annual paid next period stays owned after list return','2028-10-01' in active(page).inner_text() and active(page).locator('[data-go="P-M07-RENEW-YEAR"]:visible').count()==0);page.close()

 # Independently entered system failures must establish the same persistent block.
 recovered={'resumed','resumedstream','ownerresumed','budgetresumed','budgetmemberresumed'}
 for scene in [x for x in M['scenes'] if x.get('family')=='credits' and x.get('key') not in recovered]:
  page=new(scene['id']);click(page,'首页');click(page,'打开助手');active(page).get_by_role('textbox',name='消息',exact=True).fill('未核验不得发送');ck(scene['id']+' independent blocked state survives ordinary navigation',active(page).locator('button[type=submit]').is_disabled());page.close()
 for suffix in ['', '-ENT']:
  menu='P-M10-MENU-RESPONSIBILITY'+suffix;target='P-M10-RESPONSIBILITY-BROWSER'+suffix;settings='P-M10-SETTINGS'+suffix
  page=new(menu);ck(menu+' hides write creator entry',active(page).locator('[data-go="P-M10-CREATOR-BROWSER'+suffix+'"]:visible').count()==0);ck(menu+' shows responsibility only',active(page).locator('[data-go="'+target+'"]').is_visible() and '资格有效' not in active(page).locator('[data-go="'+target+'"]').inner_text());active(page).locator('[data-go="'+target+'"]').click();page.wait_for_timeout(130);click(page,'取消本次前往');ck('responsibility cancels into original '+menu,page.evaluate('document.body.dataset.currentScene')==menu)
  active(page).locator('[data-go="'+settings+'"]').first.click();page.wait_for_timeout(130);ck(settings+' consumes same read-only qualification','创作者资格已失效' in active(page).inner_text() and active(page).locator('[data-go="P-M10-CREATOR-BROWSER'+suffix+'"]:visible').count()==0);active(page).locator('[data-go="'+target+'"]:visible').click();page.wait_for_timeout(130);click(page,'返回 Polo');ck(menu+' return does not grant creator write','RETURN' in page.evaluate('document.body.dataset.currentScene'));click(page,'重新核对资格');click(page,'返回账号菜单');ck(menu+' verified result remains read-only',active(page).locator('[data-go="'+target+'"]').is_visible() and active(page).locator('[data-go="P-M10-CREATOR-BROWSER'+suffix+'"]:visible').count()==0);click(page,'首页');click(page,'管理技能');click(page,'首页');dest='P-M10-MENU'+suffix;active(page).locator('[data-go="'+dest+'"]').first.click();page.wait_for_timeout(130);ck(menu+' ordinary consumers retain responsibility state',active(page).locator('[data-go="'+target+'"]').is_visible() and active(page).locator('[data-go="P-M10-CREATOR-BROWSER'+suffix+'"]:visible').count()==0);page.close()
  for state,label,dest in [('BROWSER-FAILED','重试打开','BROWSER'),('QUERY-FAILED','重试查询','RETURN')]:
   page=new('P-M10-RESPONSIBILITY-'+state+suffix);click(page,label);ck(menu+' '+state+' recovers correct target',page.evaluate('document.body.dataset.currentScene')=='P-M10-RESPONSIBILITY-'+dest+suffix);page.close()
 for sid in ['P-M10-MENU','P-M10-MENU-NOPRIV']:
  page=new(sid);ck(sid+' does not invent former creator responsibility',active(page).locator('[data-go^="P-M10-RESPONSIBILITY-BROWSER"]:visible').count()==0);page.close()

 page=new('P-M07-EXPIRED');click(page,'首页');click(page,'通知');active(page).locator('[data-go="P-M07-DETAIL-PAID"]').click();page.wait_for_timeout(130);ck('expired notification chooses restore not monthly renewal',active(page).get_by_role('button',name='续费恢复',exact=True).is_visible() and active(page).get_by_role('button',name='续费',exact=True).count()==0);click(page,'续费恢复');ck('expired notification does not claim purchase limit','实际支付成功时刻' in active(page).locator('.dialog').inner_text() and '已达提前购买上限' not in active(page).locator('.dialog').inner_text());click(page,'取消');ck('cancel expired notification recovery leaves source expired',page.evaluate('document.body.dataset.currentScene')=='P-M07-EXPIRED')
 for label in ['续费恢复','去浏览器支付','返回 Polo','查询原订单和资格','续费']:click(page,label)
 ck('notification recovery now receives active latest quote','2026-11-02 至 2026-12-02' in active(page).locator('.dialog').inner_text());page.close()
 page=new('P-M07-DETAIL-PAID-SUBSCRIPTION');click(page,'退出圈子');click(page,'确认退出');click(page,'首页');click(page,'通知');active(page).locator('[data-go="P-M07-DETAIL-PAID"]').click();page.wait_for_timeout(130);ck('left circle notification offers explicit rejoin',active(page).get_by_role('button',name='重新加入圈子',exact=True).is_visible() and active(page).get_by_role('button',name='续费',exact=True).count()==0);click(page,'重新加入圈子');click(page,'取消本次前往');click(page,'首页');ck('cancel notification rejoin preserves revoked sole source',active(page).locator('[data-app-key="brand"] button').first.is_disabled());page.close()

 browser.close()
report['passed']=all(c['passed'] for c in report['checks']) and not report['errors'];(E/'product-closure.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'passed':report['passed'],'checks':len(report['checks']),'errors':report['errors']},ensure_ascii=False));raise SystemExit(0 if report['passed'] else 1)
