#!/usr/bin/env python3
"""r14 product interactions and scaled layout fixtures; no real services involved."""
from pathlib import Path
import hashlib,json,os
from playwright.sync_api import sync_playwright
R=Path(__file__).resolve().parents[3];B=R/'docs/mvp-complete-flow-hifi';A=R/'design-demos/polo-client-source-baseline';E=B/os.environ.get('POLO_REVIEW_EVIDENCE','evidence/r15');E.mkdir(parents=True,exist_ok=True)
M=json.loads((B/'prototype-manifest.json').read_text());by={s['id']:s for s in M['scenes']}
report={'revision':M['revision'],'artifacts':{str(p.relative_to(R)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [B/'prototype-manifest.json',B/'prototype.html',B/'review.html',A/'prototype.html']},'checks':[],'errors':[],'limitations':['Prototype data only; scaled DOM fixtures verify layout, not product capacity or authorization.']}
def ck(name,ok):
 report['checks'].append({'name':name,'passed':bool(ok)})
 if not ok:print('FAIL',name,flush=True)
def frame(page):return page.locator('[data-assistant-viewport]' if by[page.evaluate('document.body.dataset.currentScene')]['surface']=='assistant' else '[data-prototype-viewport]').element_handle().content_frame()
def goto(page,sid):
 page.wait_for_timeout(70);page.evaluate('(s)=>location.hash="scene="+s',sid);page.wait_for_function('(s)=>document.body.dataset.currentScene===s',arg=sid);f=frame(page);f.wait_for_function('(s)=>document.body.dataset.currentScene===s',arg=sid);return f
def clickgo(page,f,selector,target):
 f.locator('[data-prototype-scene]:visible').locator(selector).first.click();page.wait_for_function('(s)=>document.body.dataset.currentScene===s',arg=target);return frame(page)
with sync_playwright() as p:
 b=p.chromium.launch();page=b.new_page(viewport={'width':1500,'height':1000});page.set_default_timeout(8000);page.on('pageerror',lambda e:report['errors'].append(str(e)));page.goto((B/'review.html').as_uri()+'#scene=P-M03-HOME-PERSONAL');page.wait_for_timeout(200)
 f=goto(page,'P-M03-HOME-PERSONAL');ck('assistant permanently first',f.locator('.scene.active [data-app-key]').first.get_attribute('data-app-key')=='assistant')
 f.locator('[data-prototype-scene]:visible').get_by_label('搜索应用',exact=True).fill('不存在的应用');ck('search empty feedback',f.locator('.scene.active [data-library-empty]').is_visible());f.get_by_role('button',name='清空筛选').click();ck('all owned apps discoverable',f.locator('[data-app-key]:visible').count()==5)
 f.locator('[data-prototype-scene]:visible').get_by_label('应用来源').select_option(label='晨星设计圈');ck('source filter includes deduplicated shared app',f.locator('.scene.active [data-app-key="meeting"]').is_visible() and not f.locator('.scene.active [data-app-key="report"]').is_visible());f.locator('[data-prototype-scene]:visible').get_by_label('应用来源').select_option('all')
 f=goto(page,'P-M07-DETAIL-FOCUS');f=clickgo(page,f,'[data-go="P-M04-APP-GROWTH"]','P-M04-APP-GROWTH');f=clickgo(page,f,'[data-go="P-M03-HOME-PERSONAL"]','P-M03-HOME-PERSONAL');f.locator('[data-prototype-scene]:visible').get_by_label('应用来源').select_option('all');ck('circle opening updates home recency',f.locator('.scene.active [data-app-key]').nth(1).get_attribute('data-app-key')=='growth')
 for sid in ['P-M03-HOME-ZERO','P-M03-HOME-EMPTY-DIR','P-M03-HOME-LOAD-FAIL']:
  f=goto(page,sid);ck(sid+' no manual favorites','挑常用' not in f.locator('.scene.active').inner_text() and '最多 5' not in f.locator('.scene.active').inner_text())
 f=goto(page,'P-M03-HOME-ENT');ck('enterprise no circle entry',f.locator('.scene.active [data-go="P-M07-LIST"]').count()==0 and f.locator('.scene.active [data-app-key="assistant"] [data-go="A-enterprise-skills"]').is_visible());ck('enterprise no personal resources','晨星设计圈' not in f.locator('.scene.active .workspace-main').inner_text())
 f=goto(page,'P-M07-LIST');f.locator('[data-prototype-scene]:visible').get_by_label('圈子状态').select_option('restore');ck('future expiry is not revoked',f.locator('.circle-card:visible').count()==0);f.locator('[data-prototype-scene]:visible').get_by_label('圈子状态').select_option('valid');ck('valid circles filter',f.locator('.circle-card:visible').count()==4)
 f=goto(page,'P-M07-DETAIL-PAID-SUBSCRIPTION');ck('circle section indicates current tab',f.locator('.scene.active .r14-tabs [aria-current=page]').inner_text()=='订阅');ck('paid circle exit keeps identity',all(x=='P-M07-LEAVE-PAID' for x in f.get_by_role('button',name='退出圈子',exact=True).evaluate_all('(xs)=>xs.map(x=>x.dataset.go)')))
 f=goto(page,'P-M10-SETTINGS-DEVICE');f.locator('[data-prototype-scene]:visible').get_by_label('网络连接').select_option(label='直接连接');f.get_by_role('button',name='保存设置').click();f=goto(page,'P-M10-SETTINGS-ENT-DEVICE');ck('global device settings shared across spaces',f.locator('[data-prototype-scene]:visible').get_by_label('网络连接').input_value()=='直接连接')
 f=goto(page,'A-personal-preferences');f.get_by_role('button',name='回答偏好',exact=True).click();f.locator('[data-prototype-scene]:visible').get_by_label('助手如何称呼你').fill('个人称呼');f.get_by_role('button',name='保存偏好').click();f.get_by_role('button',name='输入与发送',exact=True).click();f.get_by_role('button',name='回答偏好',exact=True).click();ck('preference values survive category change',f.locator('[data-prototype-scene]:visible').get_by_label('助手如何称呼你').input_value()=='个人称呼')
 f=goto(page,'A-enterprise-preferences');f.get_by_role('button',name='回答偏好',exact=True).click();ck('assistant preferences isolated',f.locator('[data-prototype-scene]:visible').get_by_label('助手如何称呼你').input_value()!='个人称呼')
 f=goto(page,'A-personal-preferences');f.locator('[data-prototype-scene]:visible').get_by_label('助手如何称呼你').fill('未保存');page.once('dialog',lambda d:d.dismiss());f.get_by_role('button',name='首页',exact=True).first.click();ck('cancel dirty leave retains draft',page.evaluate('document.body.dataset.currentScene')=='A-personal-preferences' and f.locator('[data-prototype-scene]:visible').get_by_label('助手如何称呼你').input_value()=='未保存');f.get_by_role('button',name='保存偏好').click()
 f=goto(page,'A-personal-detail');f.get_by_role('button',name='查看内置技能').click();ck('built-in has own details','随客户端提供' in f.locator('.polo-skill-detail').inner_text());f.get_by_role('button',name='停用内置技能',exact=True).click();page.wait_for_function("()=>document.body.dataset.currentScene==='A-personal-builtinoff'");f=frame(page);ck('built-in toggle affects built-in',f.get_by_role('button',name='启用内置技能',exact=True).is_visible());f.get_by_role('button',name='启用内置技能',exact=True).click()
 f=goto(page,'A-personal-updatefailed');ck('failed update keeps verified version','仍使用已验证的 1.0.0' in f.locator('.polo-skill-detail').inner_text());f=goto(page,'A-personal-restricted');ck('last source blocks invocation','当前不可调用' in f.locator('.polo-skill-detail').inner_text())
 f=goto(page,'A-personal-new');f.get_by_role('textbox',name='消息',exact=True).fill('后台恢复验证');f.get_by_role('button',name='发送消息',exact=True).click();page.wait_for_function("()=>document.body.dataset.currentScene==='A-personal-generating'");f=frame(page);ck('assistant retains host bar',f.locator('.polo-host-bar').is_visible());f.get_by_role('button',name='关闭助手标签',exact=True).click();page.wait_for_function("()=>document.body.dataset.currentScene==='A-personal-close'");f=frame(page);f.get_by_role('button',name='后台继续',exact=True).click();page.wait_for_function("()=>document.body.dataset.currentScene==='P-M03-HOME-PERSONAL'");f=frame(page);f.get_by_role('button',name='后台任务',exact=True).click();page.wait_for_function("()=>document.body.dataset.currentScene==='P-M04-RUNTIME-PERSONAL'");f=frame(page);f.get_by_role('button',name='查看助手任务').click();page.wait_for_function("()=>document.body.dataset.currentScene==='A-personal-activity'");f=frame(page);ck('background task remains discoverable','正在执行' in f.locator('.polo-preferences').inner_text());f.get_by_role('button',name='返回原会话').click();page.wait_for_function("()=>document.body.dataset.currentScene==='A-personal-generating'");f=frame(page);ck('background returns original content','后台恢复验证' in f.locator('.mvp-chat-column').inner_text());f.get_by_role('button',name='停止生成',exact=True).click();f=goto(page,'A-personal-activity');ck('stopped activity clears running state','当前没有运行' in f.locator('.polo-preferences').inner_text())
 # A cold assistant entry has no native session yet: first handoff must request live state.
 cold=b.new_page(viewport={'width':1500,'height':1000});cold.goto((B/'review.html').as_uri()+'#scene=A-personal-new');cold.wait_for_timeout(180);cf=frame(cold);cf.get_by_role('textbox',name='消息',exact=True).fill('冷启动跨空间');cf.get_by_role('button',name='发送消息',exact=True).click();cold.wait_for_function("()=>document.body.dataset.currentScene==='A-personal-generating'");cf=goto(cold,'P-M02-CONFIRM-PERSONAL');cf.locator('.scene.active [data-assistant-switch-row]').wait_for(state='visible');ck('cold assistant entry requests current activity',cf.locator('.scene.active [data-assistant-switch-row]').is_visible());cf=clickgo(cold,cf,'[data-go="P-M03-HOME-ENT"]','P-M03-HOME-ENT');cf=goto(cold,'A-personal-activity');ck('cold assistant switch stops original task','当前没有运行' in cf.locator('.polo-preferences').inner_text());cold.close()
 # Cross-surface stop must be acknowledged before changing current space.
 f=goto(page,'A-personal-new');f.get_by_role('textbox',name='消息',exact=True).fill('切换前运行');f.get_by_role('button',name='发送消息',exact=True).click();page.wait_for_function("()=>document.body.dataset.currentScene==='A-personal-generating'")
 f=goto(page,'P-M02-CONFIRM-PERSONAL');ck('switch lists live assistant',f.locator('.scene.active [data-assistant-switch-row]').is_visible());f=clickgo(page,f,'.dialog [data-go="P-M02-SWITCHER-PERSONAL"]','P-M02-SWITCHER-PERSONAL');f=goto(page,'A-personal-activity');ck('cancel switch keeps assistant running','正在执行' in f.locator('.polo-preferences').inner_text())
 f=goto(page,'P-M02-CONFIRM-PERSONAL');f=clickgo(page,f,'[data-go="P-M03-HOME-ENT"]','P-M03-HOME-ENT');f=goto(page,'A-personal-activity');ck('switch clears old space running activity','当前没有运行' in f.locator('.polo-preferences').inner_text());f=goto(page,'A-personal-stopped');ck('stopping on switch preserves original content','切换前运行' in f.locator('.mvp-chat-column').inner_text())
 f=goto(page,'A-enterprise-new');f.get_by_role('textbox',name='消息',exact=True).fill('企业切换前运行');f.get_by_role('button',name='发送消息',exact=True).click();page.wait_for_function("()=>document.body.dataset.currentScene==='A-enterprise-generating'");f=goto(page,'P-M02-CONFIRM');f=clickgo(page,f,'[data-go="P-M02-STOPPING"]','P-M02-STOPPING');page.wait_for_function("()=>document.body.dataset.currentScene==='P-M03-HOME-PERSONAL'");f=goto(page,'A-enterprise-activity');ck('enterprise switch stops old assistant','当前没有运行' in f.locator('.polo-preferences').inner_text())
 for width,height in [(1440,900),(1024,768),(800,600)]:
  page.locator('[data-viewport-select]').select_option(f'desktop-{width}x{height}',force=True)
  for sid in ['P-M03-HOME-PERSONAL','A-personal-new','A-personal-detail','P-M07-LIST','P-M10-SETTINGS','A-personal-preferences','P-M01-LOGIN-PASSWORD','P-M02-STOP-FAILED','P-M09-BROWSER','P-M11-REVOKE','A-personal-files','A-personal-preblock']:
   page.locator('[data-reset]').evaluate('(el)=>el.click()');page.wait_for_timeout(70);f=goto(page,sid);ck(f'{sid} {width} no horizontal overflow',f.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));page.screenshot(path=str(E/(sid+f'-{width}x{height}.png')))
  if width==1024:
   f=goto(page,'A-personal-detail');ck('medium skill details stay usable',f.locator('.polo-skill-detail').bounding_box()['width']>=400);page.screenshot(path=str(E/'skills-medium-layout.png'))
  if width==800:
   f=goto(page,'A-personal-detail');f.get_by_role('button',name='有更新',exact=True).click();f.get_by_role('button',name='查看来源技能').click();ck('narrow skill drilldown',f.get_by_role('button',name='返回技能列表').is_visible());f.get_by_role('button',name='返回技能列表').click();ck('narrow list return preserves filter',f.get_by_role('button',name='有更新',exact=True).get_attribute('class')=='selected');page.screenshot(path=str(E/'skills-narrow-return.png'))
 # Extra records only inside this browser test; verify scroll geometry, not claimed catalog content.
 f=goto(page,'P-M03-HOME-PERSONAL');f.evaluate("""()=>{const g=document.querySelector('.scene.active .r14-app-grid'),c=g.lastElementChild;for(let i=0;i<40;i++){let n=c.cloneNode(true);n.querySelector('h3').textContent='布局验证应用 '+i;g.append(n)}}""");ck('large app collection scrolls vertically',f.locator('.scene.active .workspace-main').evaluate('(x)=>x.scrollHeight>x.clientHeight'));page.screenshot(path=str(E/'apps-scale-800x600.png'))
 f=goto(page,'P-M07-LIST');f.evaluate("""()=>{const g=document.querySelector('.scene.active .circle-list'),c=g.lastElementChild;for(let i=0;i<25;i++){const n=c.cloneNode(true);g.append(n)}}""");ck('many circles scroll vertically',f.locator('.scene.active .workspace-main').evaluate('(x)=>x.scrollHeight>x.clientHeight'));page.screenshot(path=str(E/'circles-scale-800x600.png'))
 f=goto(page,'A-personal-detail');f.get_by_role('button',name='全部技能',exact=True).click();f.evaluate("""()=>{const g=document.querySelector('.polo-skill-results'),c=g.querySelector('.polo-skill-summary');for(let i=0;i<70;i++){const n=c.cloneNode(true);n.querySelector('strong').textContent='布局验证技能 '+i;g.append(n)}}""");ck('many skills scroll within list',f.locator('.polo-skill-results').evaluate('(x)=>x.scrollHeight>x.clientHeight'));page.screenshot(path=str(E/'skills-scale-800x600.png'))
 b.close()
report['passed']=all(x['passed'] for x in report['checks']) and not report['errors'];(E/'workbench-browser.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'passed':report['passed'],'checks':len(report['checks']),'errors':report['errors']},ensure_ascii=False));raise SystemExit(0 if report['passed'] else 1)
