import { describe, expect, it } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const electronRoot = join(import.meta.dir, '..')
const integrationScript = readFileSync(
  join(electronRoot, 'resources', 'scripts', 'windows-terminal-integration.ps1'),
  'utf8',
)
const afterPack = readFileSync(join(import.meta.dir, 'afterPack.cjs'), 'utf8')

describe('Windows terminal integration packaging', () => {
  it('generates CLI commands that invoke bundled Bun and the CLI bundle directly', () => {
    expect(integrationScript).toContain('resources\\vendor\\bun\\bun.exe')
    expect(integrationScript).toContain('dist\\cli\\polo-cli.js')
    expect(integrationScript).toContain('"$bunPath" run "$cliPath" %*')
    expect(integrationScript).not.toContain('"$exePath" --polo-cli')
    expect(integrationScript).toContain('if /I "%~1"=="app"')
  })

  it('persists PATH ownership and only removes entries owned by Polo', () => {
    expect(integrationScript).toContain('pathEntryAddedByPolo')
    expect(integrationScript).toContain('Get-StateFileRecord')
    expect(integrationScript).toContain('Get-Sha256')
    expect(integrationScript).toContain('Test-StateOwnedFile')
    expect(integrationScript).toContain('schemaVersion = 2')
    expect(integrationScript).toContain('A pre-existing entry without Polo state belongs to the user.')
    expect(integrationScript).toContain('Test-LegacyPoloLauncher')
    expect(integrationScript).toContain('$legacyPathEntryOwned')
    expect(integrationScript).not.toContain('function Is-Managed')
    expect(integrationScript).not.toContain('-match $Pattern')
  })

  it('uses strict full-content history only when hash state is unavailable', () => {
    expect(integrationScript).toContain('Test-ExactContent')
    expect(integrationScript).toContain('Get-HistoricalLauncherAllowlist')
    expect(integrationScript).toContain('Polo cannot replace')
    expect(integrationScript).toContain('modified or user-owned file unchanged')
  })

  it('afterPack validates the launcher generated by the installer script', () => {
    expect(afterPack).toContain("'-Mode',")
    expect(afterPack).toContain("'Validate',")
    expect(afterPack).toContain('windowsInstallerScript')
    expect(afterPack).toContain('unpacked installer launcher execution failed')
  })
})
