import { describe, expect, it } from 'bun:test'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

const electronRoot = join(import.meta.dir, '..')
const integrationScript = readFileSync(
  join(electronRoot, 'resources', 'scripts', 'windows-terminal-integration.ps1'),
  'utf8',
)
const launcherTemplate = readFileSync(
  join(electronRoot, 'resources', 'bin', 'polo.cmd'),
  'utf8',
)
const afterPack = readFileSync(join(import.meta.dir, 'afterPack.cjs'), 'utf8')

describe('Windows terminal integration packaging', () => {
  it('installs the checked-in self-relative launcher template verbatim', () => {
    expect(integrationScript).toContain('[IO.File]::ReadAllText($launcherTemplate)')
    expect(integrationScript).toContain('[IO.File]::ReadAllText($legacyLauncherTemplate)')
    expect(integrationScript).toContain('polo-install-root.txt')
    expect(integrationScript).not.toContain('"$exePath" --polo-cli')
    expect(launcherTemplate).toContain('%~dp0polo-install-root.txt')
    expect(launcherTemplate).toContain('"%POLO_AI_BUN%" run "%POLO_AI_CLI_ENTRY%" %*')
    expect(launcherTemplate).not.toContain('if /I "%~1"=="app"')
  })

  it('persists PATH ownership and only removes entries owned by Polo', () => {
    expect(integrationScript).toContain('pathEntryAddedByPolo')
    expect(integrationScript).toContain('Get-StateFileRecord')
    expect(integrationScript).toContain('Get-Sha256')
    expect(integrationScript).toContain('Test-StateOwnedFile')
    expect(integrationScript).toContain('schemaVersion = 2')
    expect(integrationScript).toContain('@($launcher, $legacyLauncher, $rootPointer)')
    expect(integrationScript).toContain('A pre-existing entry without Polo state belongs to the user.')
    expect(integrationScript).toContain('Test-LegacyPoloLauncher')
    expect(integrationScript).toContain('$legacyPathEntryOwned')
    expect(integrationScript).not.toContain('function Is-Managed')
    expect(integrationScript).not.toContain('-match $Pattern')
  })

  it('uses strict full-content history only when hash state is unavailable', () => {
    expect(integrationScript).toContain('Test-ExactContent')
    expect(integrationScript).toContain('Get-HistoricalLauncherAllowlist')
    expect(integrationScript).toContain('Polo cannot replace')
    expect(integrationScript).toContain('modified or user-owned file unchanged')
    expect(integrationScript).toContain('$stateMissing = -not (Test-Path -LiteralPath $stateFile)')
    expect(integrationScript).toContain('ownership state is invalid')
    expect(integrationScript).not.toContain('return @($previousRoot')
  })

  it('afterPack validates the launcher generated by the installer script', () => {
    expect(afterPack).toContain("'-Mode',")
    expect(afterPack).toContain("'Validate',")
    expect(afterPack).toContain('windowsInstallerScript')
    expect(afterPack).toContain('unpacked installer launcher execution failed')
  })
})
