import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const root = join(import.meta.dir, '..')
const localeDir = join(root, 'packages', 'shared', 'src', 'i18n', 'locales')
const outputDir = join(root, 'apps', 'electron', 'resources', 'bin')
const locales = ['en', 'de', 'es', 'hu', 'ja', 'pl', 'zh-Hans'] as const
const localePrefixes: Record<(typeof locales)[number], string> = {
  en: 'en',
  de: 'de',
  es: 'es',
  hu: 'hu',
  ja: 'ja',
  pl: 'pl',
  'zh-Hans': 'zh',
}
const messages = Object.fromEntries(
  locales.map((locale) => {
    const catalog = JSON.parse(
      readFileSync(join(localeDir, `${locale}.json`), 'utf8'),
    ) as Record<string, string>
    const runtime = catalog['cli.bundledRuntimeMissing']
    const terminal = catalog['cli.terminalFilesMissing']
    const deprecated = catalog['cli.deprecatedCommand']
    if (!runtime || !terminal || !deprecated) {
      throw new Error(`Wrapper message key is missing from ${locale}.json`)
    }
    return [locale, { runtime, terminal, deprecated }]
  }),
) as Record<(typeof locales)[number], {
  runtime: string
  terminal: string
  deprecated: string
}>

const shellQuote = (value: string) => `'${value.replaceAll("'", "'\"'\"'")}'`
const shellCases = locales
  .filter((locale) => locale !== 'en')
  .map((locale) => {
    const prefix = localePrefixes[locale]
    const message = messages[locale]
    return `    ${prefix}|${prefix}[_-]*)
      POLO_MSG_RUNTIME=${shellQuote(message.runtime)}
      POLO_MSG_FILES=${shellQuote(message.terminal)}
      POLO_MSG_DEPRECATED=${shellQuote(message.deprecated)}
      ;;`
  })
  .join('\n')
const unixOutput = `#!/bin/sh
# Generated by scripts/generate-wrapper-messages.ts from locale JSON. Do not edit.
polo_load_wrapper_messages() {
  POLO_MSG_RUNTIME=${shellQuote(messages.en.runtime)}
  POLO_MSG_FILES=${shellQuote(messages.en.terminal)}
  POLO_MSG_DEPRECATED=${shellQuote(messages.en.deprecated)}
  case "$1" in
${shellCases}
  esac
}
`

const escapeBatch = (value: string) => value.replaceAll('%', '%%')
const batchCases = locales
  .filter((locale) => locale !== 'en')
  .map((locale) => {
    const prefix = localePrefixes[locale]
    const message = messages[locale]
    return `if /I "%POLO_MESSAGE_LOCALE:~0,2%"=="${prefix}" (
  set "POLO_MSG_RUNTIME=${escapeBatch(message.runtime)}"
  set "POLO_MSG_FILES=${escapeBatch(message.terminal)}"
  set "POLO_MSG_DEPRECATED=${escapeBatch(message.deprecated)}"
)`
  })
  .join('\n')
const windowsOutput = `@echo off
rem Generated by scripts/generate-wrapper-messages.ts from locale JSON. Do not edit.
set "POLO_MESSAGE_LOCALE=%~1"
set "POLO_MSG_RUNTIME=${escapeBatch(messages.en.runtime)}"
set "POLO_MSG_FILES=${escapeBatch(messages.en.terminal)}"
set "POLO_MSG_DEPRECATED=${escapeBatch(messages.en.deprecated)}"
${batchCases}
set "POLO_MESSAGE_LOCALE="
exit /b 0
`

const outputs = [
  [join(outputDir, 'polo-messages.sh'), unixOutput],
  [join(outputDir, 'polo-messages.cmd'), windowsOutput],
] as const
const check = process.argv.includes('--check')
for (const [path, content] of outputs) {
  if (check) {
    if (readFileSync(path, 'utf8') !== content) {
      throw new Error(`Generated wrapper messages are stale: ${path}`)
    }
  }
  else {
    writeFileSync(path, content)
  }
}
