/**
 * Script to generate icons.ts with base64 encoded icons
 * Run with: npx tsx apps/electron/src/renderer/playground/registry/generate-icons.ts
 */

import * as fs from 'fs'
import * as path from 'path'
import { fileURLToPath } from 'url'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const TOOL_ICONS_DIR = path.join(process.env.HOME!, '.polo-ai/tool-icons')
const SOURCES_DIR = path.join(
  process.env.HOME!,
  '.polo-ai/workspaces/046a02d0-6521-98eb-8756-95ec4bb8c41f/sources'
)
const OUTPUT_FILE = path.join(__dirname, 'sample-icons.ts')

// Native tools we want to include (mapped to their file names in tool-icons/)
const NATIVE_TOOLS: Record<string, string> = {
  git: 'git.ico',
  npm: 'npm.png',
  docker: 'docker.png',
  github: 'github.png',
  kubernetes: 'kubernetes.png',
  jest: 'jest.png',
  terraform: 'terraform.png',
  aws: 'amazonaws.png',
  node: 'nodejs.png',
  python: 'python.ico',
  postgresql: 'postgresql.png',
  rust: 'rust.png',
  go: 'go.png',
  eslint: 'eslint.png',
  prettier: 'prettier.png',
}

// Sources we want to include (mapped to their icon files)
const SOURCES: Record<string, string> = {
  slack: 'slack/icon.png',
  gmail: 'gmail/icon.svg',
  stripe: 'stripe/icon.svg',
  clickup: 'clickup/icon.ico',
  sentry: 'sentry/icon.png',
  playwright: 'playwright/icon.png',
  exa: 'exa/icon.png',
}

function getMimeType(filePath: string): string {
  const ext = path.extname(filePath).toLowerCase()
  switch (ext) {
    case '.png':
      return 'image/png'
    case '.svg':
      return 'image/svg+xml'
    case '.ico':
      return 'image/x-icon'
    case '.jpg':
    case '.jpeg':
      return 'image/jpeg'
    default:
      return 'application/octet-stream'
  }
}

function encodeIcon(filePath: string): string | null {
  try {
    if (!fs.existsSync(filePath)) {
      console.warn(`Icon not found: ${filePath}`)
      return null
    }
    const buffer = fs.readFileSync(filePath)
    const base64 = buffer.toString('base64')
    const mimeType = getMimeType(filePath)
    return `data:${mimeType};base64,${base64}`
  } catch (error) {
    console.error(`Error encoding ${filePath}:`, error)
    return null
  }
}

function generateIconsFile() {
  const nativeIcons: Record<string, string> = {}
  const sourceIcons: Record<string, string> = {}

  // Encode native tool icons
  console.log('Encoding native tool icons...')
  for (const [name, fileName] of Object.entries(NATIVE_TOOLS)) {
    const filePath = path.join(TOOL_ICONS_DIR, fileName)
    const encoded = encodeIcon(filePath)
    if (encoded) {
      nativeIcons[name] = encoded
      console.log(`  ✓ ${name}`)
    }
  }

  // Encode source icons
  console.log('\nEncoding source icons...')
  for (const [name, relativePath] of Object.entries(SOURCES)) {
    const filePath = path.join(SOURCES_DIR, relativePath)
    const encoded = encodeIcon(filePath)
    if (encoded) {
      sourceIcons[name] = encoded
      console.log(`  ✓ ${name}`)
    }
  }

  // Generate TypeScript file
  const output = `/**
 * Auto-generated icon data for playground samples
 * Generated by: npx tsx apps/electron/src/renderer/playground/registry/generate-icons.ts
 * DO NOT EDIT MANUALLY
 */

// Native tool icons (from ~/.polo-ai/tool-icons/)
export const nativeToolIcons = {
${Object.entries(nativeIcons)
  .map(([name, data]) => `  ${name}: '${data}',`)
  .join('\n')}
} as const

// Source icons (from workspace sources)
export const sourceIcons = {
${Object.entries(sourceIcons)
  .map(([name, data]) => `  ${name}: '${data}',`)
  .join('\n')}
} as const

// Helper to create simple colored circle icons for internal tools
export function createCircleIcon(color: string): string {
  const svg = \`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" fill="\${color}"/></svg>\`
  return \`data:image/svg+xml;base64,\${btoa(svg)}\`
}

// Internal tool icons
export const internalIcons = {
  session: createCircleIcon('#10B981'), // Emerald green
  docs: createCircleIcon('#3B82F6'), // Blue
  preferences: createCircleIcon('#8B5CF6'), // Purple
} as const
`

  fs.writeFileSync(OUTPUT_FILE, output)
  console.log(`\n✓ Generated ${OUTPUT_FILE}`)
  console.log(`  - ${Object.keys(nativeIcons).length} native tool icons`)
  console.log(`  - ${Object.keys(sourceIcons).length} source icons`)
}

generateIconsFile()
