import { describe, expect, it } from 'bun:test';
import type { AgentSession } from '@mariozechner/pi-coding-agent';
import { applySystemPromptOverride } from './system-prompt-override.ts';

/**
 * Regression contract for polo-ai-oss#648.
 *
 * Pi SDK 0.72.1's `session.prompt()` resets `agent.state.systemPrompt` to
 * `_baseSystemPrompt` on every turn (agent-session.js ~L796), and
 * `_baseSystemPrompt` itself can be regenerated by the SDK via
 * `_rebuildSystemPrompt()` when tools change. To survive both paths we must
 * stamp ALL THREE internals on the session — dropping any one of them
 * re-introduces the original bug:
 *   - `agent.state.systemPrompt` — what the next agent_loop turn ships to the LLM
 *   - `_baseSystemPrompt` — what the SDK falls back to when no extension override
 *   - `_rebuildSystemPrompt` — what the SDK calls on tool/resource rebuilds
 *
 * Pattern matches OpenClaw's `applySystemPromptOverrideToSession`.
 */

type StampedSession = {
  agent: { state: { systemPrompt?: string } };
  _baseSystemPrompt?: string;
  _rebuildSystemPrompt?: (toolNames: string[]) => string;
};

function makeFakeSession(): StampedSession {
  return {
    agent: { state: {} },
  };
}

describe('applySystemPromptOverride', () => {
  it('stamps state.systemPrompt', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'POLO_AI_PROMPT');
    expect(session.agent.state.systemPrompt).toBe('POLO_AI_PROMPT');
  });

  it('stamps the private _baseSystemPrompt field so session.prompt() reset survives', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'POLO_AI_PROMPT');
    expect(session._baseSystemPrompt).toBe('POLO_AI_PROMPT');
  });

  it('replaces _rebuildSystemPrompt with a constant function so tool-change rebuilds survive', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'POLO_AI_PROMPT');
    expect(typeof session._rebuildSystemPrompt).toBe('function');
    // Must return our prompt regardless of which tool names the SDK passes in.
    expect(session._rebuildSystemPrompt!(['read', 'bash'])).toBe('POLO_AI_PROMPT');
    expect(session._rebuildSystemPrompt!([])).toBe('POLO_AI_PROMPT');
  });

  it('overwrites previously stamped values on a re-application', () => {
    const session = makeFakeSession();
    applySystemPromptOverride(session as unknown as AgentSession, 'FIRST');
    applySystemPromptOverride(session as unknown as AgentSession, 'SECOND');
    expect(session.agent.state.systemPrompt).toBe('SECOND');
    expect(session._baseSystemPrompt).toBe('SECOND');
    expect(session._rebuildSystemPrompt!([])).toBe('SECOND');
  });
});
